### ISSUE TITLE
[BUG] Push Bullet Pro needed?

### ISSUE THREAD

**Issue by roflinger** [kvangent/PokeAlarm#118]
## Problem Description
crashes at start
## Your Environment

Operating System:  Win 10 64 bit Pro
Python Version: Python 2.7.12
PokemonGo-Map startup command: - crashes before 
PokeAlarm startup command: python runwebhook.py

Did the issue persist after restarting the script?: yes

## Console Output

```
	<CONSOLE OUTPUT GOES HERE>
<!--- Please describe the problem you are experiencing.  -->
2016-08-13 20:24:18,711 [  pushbullet_alarm] [   INFO] Pushing to channel None.
2016-08-13 20:24:18,711 [  pushbullet_alarm] [   INFO] Pushbullet Alarm intialized
Traceback (most recent call last):
  File "runwebhook.py", line 54, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "D:\Users\Downloads\PokeAlarm-master (3)\PokeAlarm-master\alarms\alarm_manager.py", line 41, in __init__
    self.alarms.append(Pushbullet_Alarm(alarm))
  File "D:\Users\Downloads\PokeAlarm-master (3)\PokeAlarm-master\alarms\pushbullet_alarm.py", line 19, in __init__
    push = self.sender.push_note("PokeAlarm activated!", "We will alert you about pokemon.")
  File "C:\Python27\lib\site-packages\pushbullet\pushbullet.py", line 238, in push_note
    return self._push(data)
  File "C:\Python27\lib\site-packages\pushbullet\pushbullet.py", line 267, in _push
    raise PushError(r.text)
pushbullet.errors.PushError: {"error":{"code":"pushbullet_pro_required","type":"invalid_request","message":"Pushbullet Pro is required to make this call.","cat":"­ƒÖÇ"},"error_code":"pushbullet_pro_required"}


## Your Alarms Config
<!--- Please post the config for your alarms in the space below -->
<!--- Remove all person data such as API_KEYs or CHAT_IDs -->
```json
    <CONFIG HERE>
```

## Troubleshooting Checklist
[ ] Most recent version of PokemonGo-Map
[ ] Most recent version of PokeAlarm
[ ] Checked the Wiki page for service in question

## Enhancement Description

{
			"active": "True",
			"type":"pushbullet",
			"api_key":"xxxx"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"xxxx",
			"channel":"#general"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"",
			"auth_token":"",
			"to_number":"+11234567890",
			"from_number":"+11234567890"
		},
		{
		        "active": "False",
		        "type":"telegram",
		        "chat_id":"your bot chat ID",
		        "bot_token":"your bot API"
    		},
		{
                        "active": "True",
                        "type": "pushover",
                        "app_token": "xxxx",
                        "user_key": "xxxx"
                }
## Use cases

start the script

**Comment by roflinger** [comment]
ok reached max 500 api calls ...
