### ISSUE TITLE
socket address error

### ISSUE THREAD

**Issue by moggd** [kvangent/PokeAlarm#122]
## Problem Description
Socket address error on fresh installation of PokeAlarm + PokemonGoMap

## Your Environment
Operating System:  Windows 7
Python Version: (use `python -V`)  2.7

## Console Output

```
Traceback (most recent call last):
  File "runwebhook.py", line 60, in <module>
    server.serve_forever()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 347, in serve_
forever
    self.start()
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 291, in start
    self.init_socket()
  File "C:\Python27\lib\site-packages\gevent\pywsgi.py", line 1222, in init_sock
et
    StreamServer.init_socket(self)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 80, in init_socket

    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 91, in get_listene
r
    return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, f
amily=family)
  File "C:\Python27\lib\site-packages\gevent\server.py", line 177, in _tcp_liste
ner
    sock.bind(address)
  File "<string>", line 1, in bind
socket.error: [Errno 10048] Only one usage of each socket address (protocol/netw
ork address/port) is normally permitted: ('127.0.0.1', 4000)
Exception gevent.hub.LoopExit: LoopExit('This operation would block forever', <H
ub at 0x2fc7850 select default pending=0 ref=0 resolver=<gevent.resolver_thread.
Resolver at 0x3498f50 pool=<ThreadPool at 0x3498f70 0/1/10>> threadpool=<ThreadP
ool at 0x3498f70 0/1/10>>) in <module 'threading' from 'C:\Python27\lib\threadin

## Your Alarms Config

```json
   {
	"alarms":[
		{
			"active":"True",
			"type":"pushbullet",
			"api_key":"XXXXX"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"YOUR_API_KEY",
			"channel":"#general"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "False",
			"type":"telegram",
			"bot_token":"YOUR_BOT_TOKEN",
			"chat_id":"YOUR_CHAT_ID"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
			"active": "False",
			"type": "twitter",
			"access_token": "YOUR_ACCESS_TOKEN",
			"access_secret": "YOUR_ACCESS_SECRET",
			"consumer_key": "YOUR_CONSUMER_KEY",
			"consumer_secret": "YOUR_CONSUMER_SECRET"
        }
	],
	"pokemon":{
		"Bulbasaur":"False",
		"Ivysaur":"False",
		"Venusaur":"True",
		"Charmander":"False",
		"Charmeleon":"False",
		"Charizard":"True",
		"Squirtle":"False",
		"Wartortle":"False",
		"Blastoise":"True",
		"Caterpie":"False",
		"Metapod":"False",
		"Butterfree":"False",
		"Weedle":"False",
		"Kakuna":"False",
		"Beedrill":"False",
		"Pidgey":"False",
		"Pidgeotto":"False",
		"Pidgeot":"False",
		"Rattata":"False",
		"Raticate":"False",
		"Spearow":"False",
		"Fearow":"False",
		"Ekans":"False",
		"Arbok":"False",
		"Pikachu":"False",
		"Raichu":"False",
		"Sandshrew":"False",
		"Sandslash":"False",
		"Nidoran♀":"False",
		"Nidorina":"False",
		"Nidoqueen":"False",
		"Nidoran♂":"False",
		"Nidorino":"False",
		"Nidoking":"False",
		"Clefairy":"False",
		"Clefable":"False",
		"Vulpix":"False",
		"Ninetales":"False",
		"Jigglypuff":"False",
		"Wigglytuff":"False",
		"Zubat":"False",
		"Golbat":"False",
		"Oddish":"False",
		"Gloom":"False",
		"Vileplume":"False",
		"Paras":"False",
		"Parasect":"False",
		"Venonat":"False",
		"Venomoth":"False",
		"Diglett":"False",
		"Dugtrio":"False",
		"Meowth":"False",
		"Persian":"False",
		"Psyduck":"False",
		"Golduck":"False",
		"Mankey":"False",
		"Primeape":"False",
		"Growlithe":"False",
		"Arcanine":"True",
		"Poliwag":"False",
		"Poliwhirl":"False",
		"Poliwrath":"True",
		"Abra":"False",
		"Kadabra":"False",
		"Alakazam":"True",
		"Machop":"False",
		"Machoke":"False",
		"Machamp":"True",
		"Bellsprout":"False",
		"Weepinbell":"False",
		"Victreebel":"False",
		"Tentacool":"False",
		"Tentacruel":"False",
		"Geodude":"False",
		"Graveler":"False",
		"Golem":"False",
		"Ponyta":"False",
		"Rapidash":"False",
		"Slowpoke":"False",
		"Slowbro":"False",
		"Magnemite":"False",
		"Magneton":"False",
		"Farfetch'd":"False",
		"Doduo":"False",
		"Dodrio":"False",
		"Seel":"False",
		"Dewgong":"True",
		"Grimer":"True",
		"Muk":"True",
		"Shellder":"False",
		"Cloyster":"False",
		"Gastly":"False",
		"Haunter":"False",
		"Gengar":"False",
		"Onix":"False",
		"Drowzee":"False",
		"Hypno":"False",
		"Krabby":"False",
		"Kingler":"False",
		"Voltorb":"False",
		"Electrode":"False",
		"Exeggcute":"False",
		"Exeggutor":"False",
		"Cubone":"False",
		"Marowak":"False",
		"Hitmonlee":"False",
		"Hitmonchan":"True",
		"Lickitung":"False",
		"Koffing":"False",
		"Weezing":"False",
		"Rhyhorn":"False",
		"Rhydon":"False",
		"Chansey":"True",
		"Tangela":"False",
		"Kangaskhan":"False",
		"Horsea":"False",
		"Seadra":"False",
		"Goldeen":"False",
		"Seaking":"False",
		"Staryu":"False",
		"Starmie":"False",
		"Mr. Mime":"False",
		"Scyther":"False",
		"Jynx":"False",
		"Electabuzz":"False",
		"Magmar":"False",
		"Pinsir":"False",
		"Tauros":"False",
		"Magikarp":"False",
		"Gyarados":"True",
		"Lapras":"True",
		"Ditto":"False",
		"Eevee":"False",
		"Vaporeon":"False",
		"Jolteon":"False",
		"Flareon":"False",
		"Porygon":"True",
		"Omanyte":"True",
		"Omastar":"True",
		"Kabuto":"True",
		"Kabutops":"True",
		"Aerodactyl":"True",
		"Snorlax":"True",
		"Articuno":"False",
		"Zapdos":"False",
		"Moltres":"False",
		"Dratini":"False",
		"Dragonair":"True",
		"Dragonite":"True",
		"Mewtwo":"False",
		"Mew":"False"
	}
}

```

## Troubleshooting Checklist
[X ] Most recent version of PokemonGo-Map
[X ] Most recent version of PokeAlarm
[ X] Checked the Wiki page for service in question

**Comment by brettgus** [comment]
Looks like something else is using port 4000... are you sure you're not already running it?

If not, try running it on another port.  Does that work?

**Comment by kvangent** [comment]
As @brettgus said, it looks like you have something already run on port 4000. Since you left you part of the form, I don't know for sure if its the map or not.
