### ISSUE TITLE
Error starting PokeAlarm - Telepot, Only Slack configured

### ISSUE THREAD

**Issue by intelunlimited** [kvangent/PokeAlarm#139]
## Problem Description
I got a problem when starting PokeAlarm. I only have slack configured in the alarms.json file. Please find the error below.

## Your Environment
Operating System:  Debian 8.5
Python Version: (use `python -V`)  Python 2.7.9
PokemonGo-Map startup command: `python runserver.py`  
PokeAlarm startup command: `python runwebhook.py -P 9876`

Did the issue persist after restarting the script?: yes

## Console Output
```
	Traceback (most recent call last):
  File "runwebhook.py", line 54, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "/cronjobs/pokealarm/alarms/alarm_manager.py", line 47, in __init__
    self.alarms.append(Telegram_Alarm(alarm))
  File "/cronjobs/pokealarm/alarms/Telegram/telegram_alarm.py", line 25, in __init__
    self.client.sendMessage(self.chat_id, 'PokeAlarm activated! We will alert this chat about pokemon.')
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 240, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 229, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 112, in _parse
    raise exception.BadHTTPResponse(response.status, text, response)
telepot.exception.BadHTTPResponse: Status 200 - First 500 characters are shown below:
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bots: An introduction for developers</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:title" content="Bots: An introduction for developers">
    <meta property="og:image" content="https://core.telegram.org/file/811140663/1/uHVzwsRJz3Y/a499733c59840694ca">
    <meta property="og:description" content="Bots are third-party applications that run inside Telegram. Users can in
```

## Your Alarms Config
```json
    {
        "alarms":[
                {
                        "active":"False",
                        "type":"pushbullet",
                        "api_key":"YOUR_API_KEY"
                },
                {
                        "active": "True",
                        "type":"slack",
                        "api_key":"xxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "channel":"#channel-name"
                },
                {
                        "active": "False",
                        "type":"twilio",
                        "account_sid":"YOUR_API_KEY",
                        "auth_token":"YOUR_AUTH_TOKEN",
                        "from_number":"YOUR_FROM_NUM",
                        "to_number":"YOUR_TO_NUM"
                },
                {
                        "active": "True",
                        "type":"telegram",
                        "bot_token":"YOUR_BOT_TOKEN",
                        "chat_id":"YOUR_CHAT_ID"
                },
                {
                        "active": "False",
                        "type": "pushover",
                        "app_token": "YOUR_APP_TOKEN",
                        "user_key": "YOUR_USER_KEY"
                },
                {
                        "active": "False",
                        "type": "twitter",
                        "access_token": "YOUR_ACCESS_TOKEN",
                        "access_secret": "YOUR_ACCESS_SECRET",
                        "consumer_key": "YOUR_CONSUMER_KEY",
                        "consumer_secret": "YOUR_CONSUMER_SECRET"
        }
        ],
        "pokemon":{
                "Bulbasaur":"True",
                "Ivysaur":"True",
                "Venusaur":"True",
                "Charmander":"True",
                "Charmeleon":"True",
                "Charizard":"True",
                "Squirtle":"True",
                "Wartortle":"True",
                "Blastoise":"True",
                "Caterpie":"False",
                "Metapod":"False",
                "Butterfree":"False",
                "Weedle":"False",
                "Kakuna":"False",
                "Beedrill":"False",
                "Pidgey":"False",
                "Pidgeotto":"False",
                "Pidgeot":"False",
                "Rattata":"False",
                "Raticate":"False",
                "Spearow":"False",
                "Fearow":"False",
                "Ekans":"True",
                "Arbok":"True",
                "Pikachu":"True",
                "Raichu":"True",
                "Sandshrew":"True",
                "Sandslash":"True",
                "Nidoran♀":"False",
                "Nidorina":"False",
                "Nidoqueen":"True",
                "Nidoran♂":"False",
                "Nidorino":"False",
                "Nidoking":"True",
                "Clefairy":"False",
                "Clefable":"False",
                "Vulpix":"True",
                "Ninetales":"True",
                "Jigglypuff":"False",
                "Wigglytuff":"False",
                "Zubat":"False",
                "Golbat":"False",
                "Oddish":"False",
                "Gloom":"False",
                "Vileplume":"True",
                "Paras":"False",
                "Parasect":"False",
                "Venonat":"False",
                "Venomoth":"False",
                "Diglett":"True",
                "Dugtrio":"True",
                "Meowth":"False",
                "Persian":"False",
                "Psyduck":"False",
                "Golduck":"False",
                "Mankey":"True",
                "Primeape":"True",
                "Growlithe":"True",
                "Arcanine":"True",
                "Poliwag":"False",
                "Poliwhirl":"False",
                "Poliwrath":"True",
                "Abra":"True",
                "Kadabra":"True",
                "Alakazam":"True",
                "Machop":"True",
                "Machoke":"True",
                "Machamp":"True",
                "Bellsprout":"False",
                "Weepinbell":"False",
                "Victreebel":"True",
                "Tentacool":"False",
                "Tentacruel":"False",
                "Geodude":"True",
                "Graveler":"True",
                "Golem":"True",
                "Ponyta":"True",
                "Rapidash":"True",
                "Slowpoke":"False",
                "Slowbro":"True",
                "Magnemite":"True",
                "Magneton":"True",
                "Farfetch'd":"True",
                "Doduo":"True",
                "Dodrio":"True",
                "Seel":"False",
                "Dewgong":"False",
                "Grimer":"True",
                "Muk":"True",
                "Shellder":"False",
                "Cloyster":"True",
                "Gastly":"False",
                "Haunter":"False",
                "Gengar":"True",
                "Onix":"True",
                "Drowzee":"False",
                "Hypno":"False",
                "Krabby":"False",
                "Kingler":"False",
                "Voltorb":"True",
                "Electrode":"True",
                "Exeggcute":"True",
                "Exeggutor":"True",
                "Cubone":"True",
                "Marowak":"True",
                "Hitmonlee":"True",
                "Hitmonchan":"True",
                "Lickitung":"True",
                "Koffing":"True",
                "Weezing":"True",
                "Rhyhorn":"True",
                "Rhydon":"True",
                "Chansey":"True",
                "Tangela":"True",
                "Kangaskhan":"True",
                "Horsea":"False",
                "Seadra":"False",
                "Goldeen":"False",
                "Seaking":"False",
                "Staryu":"False",
                "Starmie":"False",
                "Mr. Mime":"True",
                "Scyther":"True",
                "Jynx":"False",
                "Electabuzz":"True",
                "Magmar":"True",
                "Pinsir":"True",
                "Tauros":"True",
                "Magikarp":"False",
                "Gyarados":"True",
                "Lapras":"True",
                "Ditto":"True",
                "Eevee":"False",
                "Vaporeon":"False",
                "Jolteon":"False",
                "Flareon":"False",
                "Porygon":"True",
                "Omanyte":"True",
                "Omastar":"True",
                "Kabuto":"True",
                "Kabutops":"True",
                "Aerodactyl":"True",
                "Snorlax":"True",
                "Articuno":"True",
                "Zapdos":"True",
                "Moltres":"True",
                "Dratini":"True",
                "Dragonair":"True",
                "Dragonite":"True",
                "Mewtwo":"True",
                "Mew":"True"
        }
}

```

## Troubleshooting Checklist
[ x] Most recent version of PokemonGo-Map
[ x] Most recent version of PokeAlarm
[ x] Checked the Wiki page for service in question

**Comment by reme-dy** [comment]
The 4th alarm (Telegram) is set to True.  Change it to False and you should be set.

**Comment by intelunlimited** [comment]
That was it, I didn't see that sorry. Must have already been activated in the example alarms file. Sorry for the issue.

**Comment by reme-dy** [comment]
No worries, glad it's working for you.  Let us know if you have any other issues.
