### ISSUE TITLE
Push Bullet Issue?

### ISSUE THREAD

**Issue by newshaggy** [kvangent/PokeAlarm#14]
Get this error after getting a notification

2016-07-31 21:32:38,085 [ alarm_manager] [   INFO] Gyarados notication was triggered!
2016-07-31 21:32:39,311 [connectionpool] [   INFO] Resetting dropped connection: api.pushbullet.com
2016-07-31 21:32:41,383 [connectionpool] [  DEBUG] "POST /v2/pushes HTTP/1.1" 200 None
Traceback (most recent call last):
  File "runwebhook.py", line 45, in <module>
	app.run(debug=config['DEBUG'],host=config['HOST'], port=config['PORT'])
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 843, in run
	run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 694, in run_simple
	inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 659, in inner
	srv.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 499, in serve_forever
	HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
	self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
	self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
	self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
	self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
	self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
	self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
	self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
	self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
	self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe

**Comment by newshaggy** [comment]
sorry I see this is mentioned in the read me will experiment and close this for now
