### ISSUE TITLE
[BUG] Memory Error

### ISSUE THREAD

**Issue by rrbailey89** [kvangent/PokeAlarm#144]
## Problem Description

Just checked on the alarm and saw that it had this error on the screen 
## Your Environment

Operating System:  Windows 10
Python Version: (use `python -V`)  2.7
PokemonGo-Map startup command: `python runserver.py`  
PokeAlarm startup command: `python runwebhook.py -gf geofence.bak.txt`

Did the issue persist after restarting the script?: no

## Console Output

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "F:\Ray\Downloads\PoGoMap\PokeAlarm\alarms\alarm_manager.py", line 72, in run
    self.trigger_pkmn(data['message'])
  File "F:\Ray\Downloads\PoGoMap\PokeAlarm\alarms\alarm_manager.py", line 109, in trigger_pkmn
    if 'GEOFENCE' in config and not config['GEOFENCE'].contains(lat,lng):
  File "F:\Ray\Downloads\PoGoMap\PokeAlarm\alarms\geofence.py", line 40, in contains
    return self.polygon.encloses_point(Point(x,y))
  File "C:\Python27\lib\site-packages\sympy\geometry\polygon.py", line 533, in encloses_point
    poly = Polygon(*lit)
  File "C:\Python27\lib\site-packages\sympy\geometry\polygon.py", line 186, in __new__
    hit = si.intersection(sj)
  File "C:\Python27\lib\site-packages\sympy\geometry\line.py", line 779, in intersection
    py = simplify((a2*c1 - a1*c2) / t)
  File "C:\Python27\lib\site-packages\sympy\core\decorators.py", line 77, in __sympifyit_wrapper
    return func(a, b)
  File "C:\Python27\lib\site-packages\sympy\core\numbers.py", line 1392, in __mul__
    return Rational(self.p*other.p, self.q*other.q)
  File "C:\Python27\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Python27\lib\site-packages\sympy\core\compatibility.py", line 899, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Python27\lib\site-packages\sympy\core\numbers.py", line 1266, in __new__
    p = Rational(p)
  File "C:\Python27\lib\site-packages\sympy\core\cache.py", line 93, in wrapper
    retval = cfunc(*args, **kwargs)
  File "C:\Python27\lib\site-packages\sympy\core\compatibility.py", line 899, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Python27\lib\site-packages\sympy\core\numbers.py", line 1294, in __new__
    return Integer(p)
  File "C:\Python27\lib\site-packages\sympy\core\numbers.py", line 1741, in __new__
    _intcache[ival] = obj
MemoryError

```

**Comment by brettgus** [comment]
So, looking at your command line options, it looks like you aren't using a geofence, is that right?

**Comment by rrbailey89** [comment]
@brettgus that is correct. I forgot to put that in my original post. Also my computer has 16GB of RAM if that makes any difference.

**Comment by kvangent** [comment]
Just to clarify, you are not using a geofence and this happened?

**Comment by rrbailey89** [comment]
@kvangent no. im sorry for the confusion. I was using geofence.

**Comment by kvangent** [comment]
Seems to be an issue with Sympy. I am going to (eventually) look into alternatives since Sympy seems to be very slow. 

In the last commit I attempt to clear the cache - this may fix the problem.

Also, you may reduce the number of coordinates in your geofence might also speed it up.

Let me know if you still have issues.

**Comment by gkuiper** [comment]
Originally I was also planning to use a different library for my geofence pull request #127 , Shapely. However, that library does require additional dependencies under linux / mac (libgeos).

**Comment by kvangent** [comment]
@gkuiper Yeah I looked at the same one before settling on doing it myself. Given how slow Sympy is, I may have to redo it manually again.
