### ISSUE TITLE
[USER SPECIFIC] ImportError: No module named alarms

### ISSUE THREAD

**Issue by theresthatguy** [kvangent/PokeAlarm#180]
## Problem Description

Upon running start I receive an error about no module named alarms
## Your Environment

Operating System: Linux Mint 18 
Python Version: 2.7.12
PokemonGo-Map startup command: `python runserver.py -ss -l "39.0345781281, -94.5882255397" -wh http://127.0.0.1:4000 -nk`  
PokeAlarm startup command: `python runwebhook.py`

Did the issue persist after restarting the script?: yes

## Console Output

```
	Traceback (most recent call last):
  File "runwebhook.py", line 18, in <module>
    from alarms import config, set_config
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named alarms
```

## Your Alarms Config

alarms.json
```
    {
	"alarms":[
		{
			"active": "True",
			"type":"slack",
			"api_key":"REDACTED",
			"startup_message":"False",
			"pokemon":{
				"channel":"sightings",
				"username":"Professor Oak",
				"icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png",
				"title":"A wild <pkmn> has appeared near <addr> <postal>!",
				"url":"<gmaps>",
				"body_text":" Disappears at <12h_time> (<time_left>)."
			}
		},
		{
    	"active": "False",
    	"type": "twitter",
    	"access_token": "REDACTED",
    	"access_secret": "REDACTED",
    	"consumer_key": "REDACTED",
    	"consumer_secret": "REDACTED",
			"message": "A wild <pkmn> has appeared near <addr> <postal>! Disappears at <12h_time>."
		}
	],
	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"False",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"False",
		"From_Instinct":"False"
	},
	"pokestops":{
		"Lured":"True"
	},
	"pokemon":{
		"Bulbasaur":"False",
		"Ivysaur":"False",
		"Venusaur":"True",
		"Charmander":"False",
		"Charmeleon":"False",
		"Charizard":"True",
		"Squirtle":"False",
		"Wartortle":"False",
		"Blastoise":"True",
		"Caterpie":"False",
		"Metapod":"False",
		"Butterfree":"False",
		"Weedle":"False",
		"Kakuna":"False",
		"Beedrill":"False",
		"Pidgey":"False",
		"Pidgeotto":"False",
		"Pidgeot":"False",
		"Rattata":"False",
		"Raticate":"False",
		"Spearow":"False",
		"Fearow":"False",
		"Ekans":"False",
		"Arbok":"False",
		"Pikachu":"False",
		"Raichu":"False",
		"Sandshrew":"False",
		"Sandslash":"True",
		"Nidoran♀":"False",
		"Nidorina":"False",
		"Nidoqueen":"False",
		"Nidoran♂":"False",
		"Nidorino":"False",
		"Nidoking":"False",
		"Clefairy":"False",
		"Clefable":"False",
		"Vulpix":"False",
		"Ninetales":"True",
		"Jigglypuff":"False",
		"Wigglytuff":"True",
		"Zubat":"False",
		"Golbat":"False",
		"Oddish":"False",
		"Gloom":"False",
		"Vileplume":"False",
		"Paras":"False",
		"Parasect":"False",
		"Venonat":"False",
		"Venomoth":"False",
		"Diglett":"False",
		"Dugtrio":"False",
		"Meowth":"False",
		"Persian":"False",
		"Psyduck":"False",
		"Golduck":"False",
		"Mankey":"False",
		"Primeape":"False",
		"Growlithe":"False",
		"Arcanine":"True",
		"Poliwag":"False",
		"Poliwhirl":"False",
		"Poliwrath":"True",
		"Abra":"False",
		"Kadabra":"False",
		"Alakazam":"True",
		"Machop":"False",
		"Machoke":"False",
		"Machamp":"True",
		"Bellsprout":"False",
		"Weepinbell":"False",
		"Victreebel":"False",
		"Tentacool":"False",
		"Tentacruel":"False",
		"Geodude":"False",
		"Graveler":"False",
		"Golem":"True",
		"Ponyta":"False",
		"Rapidash":"False",
		"Slowpoke":"False",
		"Slowbro":"False",
		"Magnemite":"False",
		"Magneton":"True",
		"Farfetch'd":"True",
		"Doduo":"False",
		"Dodrio":"False",
		"Seel":"False",
		"Dewgong":"True",
		"Grimer":"False",
		"Muk":"True",
		"Shellder":"False",
		"Cloyster":"True",
		"Gastly":"False",
		"Haunter":"False",
		"Gengar":"True",
		"Onix":"True",
		"Drowzee":"False",
		"Hypno":"True",
		"Krabby":"False",
		"Kingler":"False",
		"Voltorb":"False",
		"Electrode":"True",
		"Exeggcute":"False",
		"Exeggutor":"True",
		"Cubone":"False",
		"Marowak":"False",
		"Hitmonlee":"True",
		"Hitmonchan":"True",
		"Lickitung":"True",
		"Koffing":"False",
		"Weezing":"True",
		"Rhyhorn":"False",
		"Rhydon":"True",
		"Chansey":"True",
		"Tangela":"False",
		"Kangaskhan":"True",
		"Horsea":"False",
		"Seadra":"False",
		"Goldeen":"False",
		"Seaking":"False",
		"Staryu":"False",
		"Starmie":"False",
		"Mr. Mime":"True",
		"Scyther":"False",
		"Jynx":"True",
		"Electabuzz":"False",
		"Magmar":"False",
		"Pinsir":"False",
		"Tauros":"False",
		"Magikarp":"False",
		"Gyarados":"True",
		"Lapras":"True",
		"Ditto":"True",
		"Eevee":"False",
		"Vaporeon":"True",
		"Jolteon":"True",
		"Flareon":"True",
		"Porygon":"True",
		"Omanyte":"False",
		"Omastar":"True",
		"Kabuto":"False",
		"Kabutops":"True",
		"Aerodactyl":"True",
		"Snorlax":"True",
		"Articuno":"True",
		"Zapdos":"True",
		"Moltres":"True",
		"Dratini":"True",
		"Dragonair":"True",
		"Dragonite":"True",
		"Mewtwo":"True",
		"Mew":"True"
	}
}
```
config.ini
```
# Copy this file to config.ini and modify to suit your needs
# Uncomment a line (remove the #) when you want to change its default value. Alternatively, all of these options can be set at the command line

# Server Settings
#host: 						# Address to listen on (default 127.0.0.1)
#port: 						# Port to listen on (default: 4000)
key: redacted						# Google Maps API Key to use
#config: 					# Alarms configuration file. default: alarms.json
#location: 					# Location, can be an address or coordinates
#locale: 					# Locale for Pokemon names
#geofence: 					# Specify a file of coordinates, limiting alerts to within this area
units: imperial					# Specify either metric or imperial
#timelimit: 					# Minimum number of seconds remaining on a pokemon to notify
```

## Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokeAlarm
[X] Checked the Wiki page for service in question

First time I've had trouble since using this...

**Comment by kvangent** [comment]
You have used this before?

Can you confirm you are using the most up to date pull and can you check to see if you have an alarms folder?

**Comment by theresthatguy** [comment]
Did another git clone when I got home and copied the alarms.json and config.ini. Everything working kosher except how the messages are displayed in slack.
![screenshot_20160830-030509](https://cloud.githubusercontent.com/assets/20618895/18081272/fffbf1f8-6e5e-11e6-9a9b-f41ebde3776b.jpg)
