### ISSUE TITLE
Errors in __init__.py and api.py when running runwebhook [BUG]

### ISSUE THREAD

**Issue by Chaban93** [kvangent/PokeAlarm#190]
## Problem Description
As title says, when I try to run runwebhook I get some errors, and I can't really figure how to solve it.

## Your Environment
Operating System:  Windows 7
Python Version: 2.7
PokemonGo-Map startup command:

start C:\Python27\python.exe runserver.py -a ptc -u XXX -u XXX -u XXX -u XXX -u XXX -p XXX -k XXX -l "XXX" -st 6 -sd 10 -H 0.0.0.0 -wh http://127.0.0.1:4000
C:\Python27\python.exe runserver.py -a ptc -u XXX -p XXX -k XXX -l "XXX" -st 1 -sd 10 -H 0.0.0.0 -ns --port 5001

PokeAlarm startup command:

python runwebhook.py

Did the issue persist after restarting the script?: yes

## Console Output
```
	<2016-09-01 11:19:03,987 [     alarm_manager] [   INFO] You will be notified of t
he following pokemon:
2016-09-01 11:19:03,987 [     alarm_manager] [   INFO] Ivysaur (Unl), Venusaur (
Unl), Charmeleon (Unl), Charizard (Unl),
2016-09-01 11:19:03,987 [     alarm_manager] [   INFO] Wartortle (Unl), Blastois
e (Unl), Pidgey (Unl), Rattata (Unl),
2016-09-01 11:19:03,987 [     alarm_manager] [   INFO] Raichu (Unl)
2016-09-01 11:19:03,987 [     alarm_manager] [   INFO] Alarm not activated: push
bullet because value not set to "True"
2016-09-01 11:19:03,987 [     alarm_manager] [   INFO] Alarm not activated: push
over because value not set to "True"
2016-09-01 11:19:03,987 [     alarm_manager] [   INFO] Alarm not activated: slac
k because value not set to "True"
2016-09-01 11:19:04,019 [    connectionpool] [   INFO] Starting new HTTPS connec
tion (1): api.telegram.org
Traceback (most recent call last):
  File "runwebhook.py", line 81, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "C:\Users\user\Desktop\PokeAlarm\alarms\alarm_manager.py", line 54, in __
init__
    self.alarms.append(Telegram_Alarm(alarm))
  File "C:\Users\user\Desktop\PokeAlarm\alarms\Telegram\telegram_alarm.py", line
 54, in __init__
    self.client.sendMessage(self.pokemon['chat_id'], 'PokeAlarm activated! We wi
ll alert this chat about pokemon.')
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 240, in sendMes
sage
    return self._api_request('sendMessage', _rectify(p))
  File "C:\Python27\lib\site-packages\telepot\__init__.py", line 229, in _api_re
quest
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 131, in request
    return _parse(r)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 123, in _parse
    raise e(description, error_code, data)
telepot.exception.UnauthorizedError: (u'Unauthorized', 401, {u'error_code': 401,
 u'ok': False, u'description': u'Unauthorized'})>
```

## Your Alarms Config
```json
    <{
	"alarms":[
		{
			"active":"False",
			"type":"pushbullet",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "True",
			"type":"telegram",
			"bot_token":"XXX",
			"chat_id":"XXX"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "False",
			"type": "twitter",
			"access_token": "YOUR_ACCESS_TOKEN",
			"access_secret": "YOUR_ACCESS_SECRET",
			"consumer_key": "YOUR_CONSUMER_KEY",
			"consumer_secret": "YOUR_CONSUMER_SECRET"
        }
	],
	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"False",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"False",
		"From_Instinct":"False"
	},
	"pokestops":{
		"Lured":"true"
	},
	"pokemon":{
		"Bulbasaur":"False",
		"Ivysaur":"True",
		"Venusaur":"True",
		"Charmander":"False",
		"Charmeleon":"True",
		"Charizard":"True",
		"Squirtle":"False",
		"Wartortle":"True",
		"Blastoise":"True",
		"Caterpie":"False",
		"Metapod":"False",
		"Butterfree":"False",
		"Weedle":"False",
		"Kakuna":"False",
		"Beedrill":"False",
		"Pidgey":"True",
		"Pidgeotto":"False",
		"Pidgeot":"False",
		"Rattata":"True",
		"Raticate":"False",
		"Spearow":"False",
		"Fearow":"False",
		"Ekans":"False",
		"Arbok":"False",
		"Pikachu":"False",
		"Raichu":"True",
		"Sandshrew":"False",
		"Sandslash":"False",
		"Nidoranâ™€":"False",
		"Nidorina":"False",
		"Nidoqueen":"False",
		"Nidoranâ™‚":"False",
		"Nidorino":"False",
		"Nidoking":"False",
		"Clefairy":"False",
		"Clefable":"False",
		"Vulpix":"False",
		"Ninetales":"False",
		"Jigglypuff":"False",
		"Wigglytuff":"False",
		"Zubat":"False",
		"Golbat":"False",
		"Oddish":"False",
		"Gloom":"False",
		"Vileplume":"False",
		"Paras":"False",
		"Parasect":"False",
		"Venonat":"False",
		"Venomoth":"False",
		"Diglett":"False",
		"Dugtrio":"False",
		"Meowth":"False",
		"Persian":"False",
		"Psyduck":"False",
		"Golduck":"False",
		"Mankey":"False",
		"Primeape":"False",
		"Growlithe":"False",
		"Arcanine":"False",
		"Poliwag":"False",
		"Poliwhirl":"False",
		"Poliwrath":"False",
		"Abra":"False",
		"Kadabra":"False",
		"Alakazam":"False",
		"Machop":"False",
		"Machoke":"False",
		"Machamp":"False",
		"Bellsprout":"False",
		"Weepinbell":"False",
		"Victreebel":"False",
		"Tentacool":"False",
		"Tentacruel":"False",
		"Geodude":"False",
		"Graveler":"False",
		"Golem":"False",
		"Ponyta":"False",
		"Rapidash":"False",
		"Slowpoke":"False",
		"Slowbro":"False",
		"Magnemite":"False",
		"Magneton":"False",
		"Farfetch'd":"False",
		"Doduo":"False",
		"Dodrio":"False",
		"Seel":"False",
		"Dewgong":"False",
		"Grimer":"False",
		"Muk":"False",
		"Shellder":"False",
		"Cloyster":"False",
		"Gastly":"False",
		"Haunter":"False",
		"Gengar":"False",
		"Onix":"False",
		"Drowzee":"False",
		"Hypno":"False",
		"Krabby":"False",
		"Kingler":"False",
		"Voltorb":"False",
		"Electrode":"False",
		"Exeggcute":"False",
		"Exeggutor":"False",
		"Cubone":"False",
		"Marowak":"False",
		"Hitmonlee":"False",
		"Hitmonchan":"False",
		"Lickitung":"False",
		"Koffing":"False",
		"Weezing":"False",
		"Rhyhorn":"False",
		"Rhydon":"False",
		"Chansey":"False",
		"Tangela":"False",
		"Kangaskhan":"False",
		"Horsea":"False",
		"Seadra":"False",
		"Goldeen":"False",
		"Seaking":"False",
		"Staryu":"False",
		"Starmie":"False",
		"Mr. Mime":"False",
		"Scyther":"False",
		"Jynx":"False",
		"Electabuzz":"False",
		"Magmar":"False",
		"Pinsir":"False",
		"Tauros":"False",
		"Magikarp":"False",
		"Gyarados":"False",
		"Lapras":"False",
		"Ditto":"False",
		"Eevee":"False",
		"Vaporeon":"False",
		"Jolteon":"False",
		"Flareon":"False",
		"Porygon":"False",
		"Omanyte":"False",
		"Omastar":"False",
		"Kabuto":"False",
		"Kabutops":"False",
		"Aerodactyl":"False",
		"Snorlax":"False",
		"Articuno":"False",
		"Zapdos":"False",
		"Moltres":"False",
		"Dratini":"False",
		"Dragonair":"False",
		"Dragonite":"False",
		"Mewtwo":"False",
		"Mew":"False"
	}
}
>
```

## Troubleshooting Checklist
[X ] Mosrt recent version of PokemonGo-Map
[X ] Most recent version of PokeAlarm
[X ] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Answered in discord - Incorrect chat-id. See the wiki for information on how to find it.
