### ISSUE TITLE
Issue -  KeyError: 'pokestops'

### ISSUE THREAD

**Issue by paulharman** [kvangent/PokeAlarm#200]
## Problem Description
Console error when starting 
KeyError: 'pokestops'

Has worked ok previously with docker.  Friend is also running in the same environment without issues.

## Your Environment

Operating System:  Docker on ubuntu

PokeAlarm startup command: `docker run -d -p 4000:4000 -v /etc/localtime:/etc/localtime:ro --restart always --name pokealarm pokealarm -H 0.0.0.0 -P 4000 -k YOUR_API_KEY -l "POSTCODE`

Did the issue persist after restarting the script?: yes

## Console Output

```
	2016-09-05 09:59:29,375 [     alarm_manager] [   INFO] You will be notified of the following pokemon:
2016-09-05 09:59:29,375 [     alarm_manager] [   INFO] Ivysaur (Unl), Venusaur (Unl), Charmeleon (Unl), Charizard (Unl),
2016-09-05 09:59:29,375 [     alarm_manager] [   INFO] Wartortle (Unl), Blastoise (Unl), Arbok (Unl), Raichu (Unl),
2016-09-05 09:59:29,375 [     alarm_manager] [   INFO] Sandslash (Unl), Nidoqueen (Unl), Nidoking (Unl), Ninetales (Unl),
2016-09-05 09:59:29,375 [     alarm_manager] [   INFO] Wigglytuff (Unl), Vileplume (Unl), Dugtrio (Unl), Persian (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Primeape (Unl), Growlithe (Unl), Arcanine (Unl), Poliwrath (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Alakazam (Unl), Machamp (Unl), Victreebel (Unl), Tentacruel (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Graveler (Unl), Golem (Unl), Rapidash (Unl), Slowbro (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Magneton (Unl), Farfetch'd (Unl), Dodrio (Unl), Muk (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Gengar (Unl), Electrode (Unl), Exeggutor (Unl), Marowak (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Hitmonlee (Unl), Hitmonchan (Unl), Weezing (Unl), Rhydon (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Chansey (Unl), Starmie (Unl), Pinsir (Unl), Tauros (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Gyarados (Unl), Lapras (Unl), Omastar (Unl), Kabuto (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Kabutops (Unl), Aerodactyl (Unl), Snorlax (Unl), Articuno (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Zapdos (Unl), Moltres (Unl), Dragonair (Unl), Dragonite (Unl),
2016-09-05 09:59:29,376 [     alarm_manager] [   INFO] Mewtwo (Unl), Mew (Unl)
Traceback (most recent call last):
  File "./runwebhook.py", line 81, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "/usr/src/app/alarms/alarm_manager.py", line 36, in __init__
    self.stop_list =  make_pokestops_list(settings["pokestops"])
KeyError: 'pokestops'

```

## Your Alarms Config

```json
    {
	"alarms":[
		{
			"active":"False",
			"type":"boxcar",
			"user_credentials":"YOUR_API_KEY"
		},
		{
			"active":"False",
			"type":"pushbullet",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
			"active": "True",
			"type":"slack",
			"api_key":"YOUR_API_KEY",
			"channel":"#alerts",
			"startup_message":"True",
			"startup_list":"True",
			"pokemon":{
        			"channel":"#alerts",
        			"username":"<pkmn>",
        			"icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png",
        			"title":"A wild <pkmn> has appeared!",
        			"url":"<gmaps>",
        			"body": "It's near <address> (<dist> from Hurley) until <12h_time> (<time_left>).",
        			"map": { 
            				"enabled":"true",
            				"width":"400",
            				"height":"250",
            				"maptype":"roadmap",
            				"zoom": "16"
        			}
    			}				
		},
		{
			"active": "True",
			"type":"slack",
			"api_key":"YOUR_API_KEY",
			"channel":"#hurleyalerts",
			"startup_message":"True",
			"startup_list":"True",
			"pokemon":{
        			"channel":"#alerts",
        			"username":"<pkmn>",
        			"icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png",
        			"title":"A wild <pkmn> has appeared!",
        			"url":"<gmaps>",
        			"body": "It's near <address> (<dist> from Hurley) until <12h_time> (<time_left>).",
        			"map": { 
            				"enabled":"true",
            				"width":"400",
            				"height":"250",
            				"maptype":"roadmap",
            				"zoom": "16"
        			}
    			}			
		},
		{
			"active": "False",
			"type":"telegram",
			"bot_token":"YOUR_BOT_TOKEN",
			"chat_id":"YOUR_CHAT_ID"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "False",
			"type": "twitter",
			"access_token": "YOUR_ACCESS_TOKEN",
			"access_secret": "YOUR_ACCESS_SECRET",
			"consumer_key": "YOUR_CONSUMER_KEY",
			"consumer_secret": "YOUR_CONSUMER_SECRET"
        }
	],
	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"False",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"False",
		"From_Instinct":"False"
	},
	"pokestops":{
		"Lured":"false"
	},
	"pokemon":{
      "Bulbasaur":"False",
      "Ivysaur":"True",
      "Venusaur":"True",
      "Charmander":"False",
      "Charmeleon":"True",
      "Charizard":"True",
      "Squirtle":"False",
      "Wartortle":"True",
      "Blastoise":"True",
      "Caterpie":"False",
      "Metapod":"False",
      "Butterfree":"False",
      "Weedle":"False",
      "Kakuna":"False",
      "Beedrill":"False",
      "Pidgey":"False",
      "Pidgeotto":"False",
      "Pidgeot":"False",
      "Rattata":"False",
      "Raticate":"False",
      "Spearow":"False",
      "Fearow":"False",
      "Ekans":"False",
      "Arbok":"True",
      "Pikachu":"False",
      "Raichu":"True",
      "Sandshrew":"False",
      "Sandslash":"True",
      "Nidoranâ™€":"False",
      "Nidorina":"False",
      "Nidoqueen":"True",
      "Nidoranâ™‚":"False",
      "Nidorino":"False",
      "Nidoking":"True",
      "Clefairy":"False",
      "Clefable":"False",
      "Vulpix":"False",
      "Ninetales":"True",
      "Jigglypuff":"False",
      "Wigglytuff":"True",
      "Zubat":"False",
      "Golbat":"False",
      "Oddish":"False",
      "Gloom":"False",
      "Vileplume":"True",
      "Paras":"False",
      "Parasect":"False",
      "Venonat":"False",
      "Venomoth":"False",
      "Diglett":"False",
      "Dugtrio":"True",
      "Meowth":"False",
      "Persian":"True",
      "Psyduck":"False",
      "Golduck":"False",
      "Mankey":"False",
      "Primeape":"True",
      "Growlithe":"True",
      "Arcanine":"True",
      "Poliwag":"False",
      "Poliwhirl":"False",
      "Poliwrath":"True",
      "Abra":"False",
      "Kadabra":"False",
      "Alakazam":"True",
      "Machop":"False",
      "Machoke":"False",
      "Machamp":"True",
      "Bellsprout":"False",
      "Weepinbell":"False",
      "Victreebel":"True",
      "Tentacool":"False",
      "Tentacruel":"True",
      "Geodude":"False",
      "Graveler":"True",
      "Golem":"True",
      "Ponyta":"False",
      "Rapidash":"True",
      "Slowpoke":"False",
      "Slowbro":"True",
      "Magnemite":"False",
      "Magneton":"True",
      "Farfetch'd":"True",
      "Doduo":"False",
      "Dodrio":"True",
      "Seel":"False",
      "Dewgong":"False",
      "Grimer":"False",
      "Muk":"True",
      "Shellder":"False",
      "Cloyster":"False",
      "Gastly":"False",
      "Haunter":"False",
      "Gengar":"True",
      "Onix":"False",
      "Drowzee":"False",
      "Hypno":"False",
      "Krabby":"False",
      "Kingler":"False",
      "Voltorb":"False",
      "Electrode":"True",
      "Exeggcute":"False",
      "Exeggutor":"True",
      "Cubone":"False",
      "Marowak":"True",
      "Hitmonlee":"True",
      "Hitmonchan":"True",
      "Lickitung":"False",
      "Koffing":"False",
      "Weezing":"True",
      "Rhyhorn":"False",
      "Rhydon":"True",
      "Chansey":"True",
      "Tangela":"False",
      "Kangaskhan":"False",
      "Horsea":"False",
      "Seadra":"False",
      "Goldeen":"False",
      "Seaking":"False",
      "Staryu":"False",
      "Starmie":"True",
      "Mr. Mime":"False",
      "Scyther":"False",
      "Jynx":"False",
      "Electabuzz":"False",
      "Magmar":"False",
      "Pinsir":"True",
      "Tauros":"True",
      "Magikarp":"False",
      "Gyarados":"True",
      "Lapras":"True",
      "Ditto":"False",
      "Eevee":"False",
      "Vaporeon":"False",
      "Jolteon":"False",
      "Flareon":"False",
      "Porygon":"False",
      "Omanyte":"False",
      "Omastar":"True",
      "Kabuto":"True",
      "Kabutops":"True",
      "Aerodactyl":"True",
      "Snorlax":"True",
      "Articuno":"True",
      "Zapdos":"True",
      "Moltres":"True",
      "Dratini":"False",
      "Dragonair":"True",
      "Dragonite":"True",
      "Mewtwo":"True",
      "Mew":"True"
	}
}
```

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
@paulharman Are you sure that you are using a the most recent version? Your alarms.json works fine for me.

**Comment by paulharman** [comment]
Hi, working fine after I started from fresh.  Had done a git pull but I guess something wasn't quite right. Thanks
