### ISSUE TITLE
[BUG] sockets not closing properly in windows with Twitter

### ISSUE THREAD

**Issue by gabaod** [kvangent/PokeAlarm#207]
## Your Environment

Operating System:  Windows 8.1
Python Version: (use `python -V`)  2.7.12
PokemonGo-Map startup command: `python runserver.py -ns -ss -wh http://10.0.10.111:4007 --wh-threads 300 -a ptc -u "**" -u "**" -p "**" -l "44.94784721543192,-93.09534328637685" -st 8 -k "***" --db-host "127.0.0.1" --db-type "mysql" --db-name "pokemon" --db-user "***" --db-pass "***" --host "10.0.10.111" --scan-delay 12`  
PokeAlarm startup command: `python runwebhook.py -H 10.0.10.111 -P 4007 `

Did the issue persist after restarting the script?: yes

## Console Output

```
	Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "C:\Python27\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 122, in __init__

    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
<WSGIServer at 0x49640b8L fileno=604 address=10.0.10.111:4004> failed with IOError

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent\baseserver.py", line 186, in _do_read
    args = self.do_read()
  File "C:\Python27\lib\site-packages\gevent\server.py", line 111, in do_read
    client_socket, address = self.socket.accept()
  File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 195, in accept
    sockobj = socket(_sock=client_socket)
  File "C:\Python27\lib\site-packages\gevent\_socket2.py", line 122, in __init__

    self._read_event = io(fileno, 1)
  File "gevent\corecext.pyx", line 480, in gevent.corecext.loop.io (gevent/gevent.corecext.c:8804)
  File "gevent\corecext.pyx", line 825, in gevent.corecext.io.__init__ (gevent/gevent.corecext.c:15470)
IOError: cannot watch more than 1024 sockets
<WSGIServer at 0x49640b8L fileno=604 address=10.0.10.111:4004> failed with IOError

2016-09-07 17:08:58,380 [     alarm_manager] [   INFO] Krabby ignored: notify not enabled.
KeyboardInterrupt
```

## Your Alarms Config

```json
    {
	"alarms":[
		{
			"active":"False",
			"type":"boxcar",
			"user_credentials":"YOUR_API_KEY"
		},
		{
			"active":"False",
			"type":"pushbullet",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"",
			"channel":"general",
			"startup_message":"True",
			"startup_list":"True"
		},
		{
			"active": "False",
			"type":"telegram",
			"bot_token":"YOUR_BOT_TOKEN",
			"chat_id":"YOUR_CHAT_ID"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "True",
			"type": "twitter",
			"access_token": "***",
			"access_secret": "***",
			"consumer_key": "***",
			"consumer_secret": "***"
        }
	],
	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"False",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"False",
		"From_Instinct":"False"
	},
	"pokestops":{
		"Lured":"false"
	},
	"pokemon":{
		"channel":"general",
		"username":"<pkmn>",
		"icon_url" : "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png",
        "title":"A wild <pkmn> has appeared!",
        "url":"<gmaps>",
        "body": "Available until <24h_time> (<time_left>).",
		"Bulbasaur":"False",
		"Ivysaur":"False",
		"Venusaur":"True",
		"Charmander":"False",
		"Charmeleon":"False",
		"Charizard":"True",
		"Squirtle":"False",
		"Wartortle":"False",
		"Blastoise":"True",
		"Caterpie":"False",
		"Metapod":"False",
		"Butterfree":"False",
		"Weedle":"False",
		"Kakuna":"False",
		"Beedrill":"False",
		"Pidgey":"False",
		"Pidgeotto":"False",
		"Pidgeot":"False",
		"Rattata":"False",
		"Raticate":"False",
		"Spearow":"False",
		"Fearow":"False",
		"Ekans":"False",
		"Arbok":"True",
		"Pikachu":"False",
		"Raichu":"True",
		"Sandshrew":"False",
		"Sandslash":"True",
		"Nidoran♀":"False",
		"Nidorina":"False",
		"Nidoqueen":"True",
		"Nidoran♂":"False",
		"Nidorino":"False",
		"Nidoking":"True",
		"Clefairy":"False",
		"Clefable":"False",
		"Vulpix":"False",
		"Ninetales":"True",
		"Jigglypuff":"False",
		"Wigglytuff":"True",
		"Zubat":"False",
		"Golbat":"False",
		"Oddish":"False",
		"Gloom":"False",
		"Vileplume":"True",
		"Paras":"False",
		"Parasect":"False",
		"Venonat":"False",
		"Venomoth":"False",
		"Diglett":"False",
		"Dugtrio":"True",
		"Meowth":"False",
		"Persian":"True",
		"Psyduck":"False",
		"Golduck":"True",
		"Mankey":"False",
		"Primeape":"True",
		"Growlithe":"False",
		"Arcanine":"True",
		"Poliwag":"False",
		"Poliwhirl":"False",
		"Poliwrath":"True",
		"Abra":"False",
		"Kadabra":"False",
		"Alakazam":"False",
		"Machop":"False",
		"Machoke":"False",
		"Machamp":"True",
		"Bellsprout":"False",
		"Weepinbell":"False",
		"Victreebel":"True",
		"Tentacool":"False",
		"Tentacruel":"False",
		"Geodude":"False",
		"Graveler":"False",
		"Golem":"False",
		"Ponyta":"False",
		"Rapidash":"True",
		"Slowpoke":"False",
		"Slowbro":"True",
		"Magnemite":"False",
		"Magneton":"True",
		"Farfetch'd":"False",
		"Doduo":"False",
		"Dodrio":"True",
		"Seel":"False",
		"Dewgong":"False",
		"Grimer":"False",
		"Muk":"False",
		"Shellder":"False",
		"Cloyster":"False",
		"Gastly":"False",
		"Haunter":"False",
		"Gengar":"True",
		"Onix":"False",
		"Drowzee":"False",
		"Hypno":"False",
		"Krabby":"False",
		"Kingler":"False",
		"Voltorb":"False",
		"Electrode":"True",
		"Exeggcute":"False",
		"Exeggutor":"True",
		"Cubone":"False",
		"Marowak":"False",
		"Hitmonlee":"False",
		"Hitmonchan":"False",
		"Lickitung":"True",
		"Koffing":"False",
		"Weezing":"False",
		"Rhyhorn":"False",
		"Rhydon":"True",
		"Chansey":"False",
		"Tangela":"True",
		"Kangaskhan":"True",
		"Horsea":"False",
		"Seadra":"False",
		"Goldeen":"False",
		"Seaking":"False",
		"Staryu":"False",
		"Starmie":"False",
		"Mr. Mime":"True",
		"Scyther":"True",
		"Jynx":"False",
		"Electabuzz":"True",
		"Magmar":"True",
		"Pinsir":"False",
		"Tauros":"False",
		"Magikarp":"False",
		"Gyarados":"True",
		"Lapras":"True",
		"Ditto":"False",
		"Eevee":"False",
		"Vaporeon":"True",
		"Jolteon":"True",
		"Flareon":"True",
		"Porygon":"True",
		"Omanyte":"False",
		"Omastar":"True",
		"Kabuto":"False",
		"Kabutops":"True",
		"Aerodactyl":"True",
		"Snorlax":"True",
		"Articuno":"False",
		"Zapdos":"False",
		"Moltres":"False",
		"Dratini":"True",
		"Dragonair":"True",
		"Dragonite":"True",
		"Mewtwo":"True",
		"Mew":"False"
	}
}

```

## Troubleshooting Checklist
[x ] Most recent version of PokemonGo-Map
[x ] Most recent version of PokeAlarm
[x ] Checked the Wiki page for service in question

--------------------------------------------------------------->

**Comment by gabaod** [comment]
update: I guess I have the same issue with the one that runs slack. is it possible running pokealarm from 3 different directories is causing this?

**Comment by kvangent** [comment]
@gabaod Does the server keep functioning after these errors? How many webhook threads on PokemonGo-Map are you running?

**Comment by kvangent** [comment]
@gabaod So it looks like you said up above that you are running 300 webhook threads. My guess is that what happens is all 300 of those threads get their own socket, Then you have a bunch of sockets that each alarm is holding open, and you have sockets for workers, etc. It looks like gevent (on Windows) is limited to only tracking 1024 and between your map and your alarms you are exceeding this. There isn't much I can do, but you can try the following:

- Move either your map or alarms to a new computer.
- Move either your map or alarms onto a machine running a linux server edition (I would suggest Ubuntu).
- If you have a reasonable computer, you can probably get away with install a VirtualBox VM of a linux server edition

**Comment by gabaod** [comment]
Thanks. Ill do some reconfiguration of how it works. Glad to know its on my end.

**Comment by dongemus** [comment]
@gabaod I found this thread a couple days ago googling my ioerror. Today I found the fix. 
In RM you make a webhook whitelist (or blacklist). Getting rid of just the top 7 "trash" pokemon can cut your webhooks in half! My PokeAlarm is working great now!
