### ISSUE TITLE
Nidoran's crash Slacker Alarm

### ISSUE THREAD

**Issue by kvangent** [kvangent/PokeAlarm#21]
`2016-08-01 20:29:22,933 [ alarm_manager] [ INFO] NidoranΓÖé notication was triggered! Exception in thread Thread-1: Traceback (most recent call last):

File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner self.run()

File "C:\Users\Keith\Desktop\PokeAlarm-master\alarms\alarm_manager.py", line 54, in run self.trigger_pkmn(data['message'])

File "C:\Users\Keith\Desktop\PokeAlarm-master\alarms\alarm_manager.py", line 85, in trigger_pkmn alarm.pokemon_alert(pkinfo)

File "C:\Users\Keith\Desktop\PokeAlarm-master\alarms\slack_alarm.py", line 34, in pokemon_alert text='<{}|{}> {}'.format(gmaps_link, notification_text, time_text), UnicodeEncodeError: 'ascii' codec can't encode character u'\u2642' in position 14: ordinal not in range(128)`

**Comment by kvangent** [comment]
Hopefully fixed with latest commit.
