### ISSUE TITLE
[USER SPECIFIC] Cannot run PokeAlert when Twitter alarm is enabled

### ISSUE THREAD

**Issue by saics72** [kvangent/PokeAlarm#233]
## Problem Description
Error occurs when trying to run PokeAlarm with Twitter enabled.

## Your Environment

Operating System:  Win 7 32 bit
Python Version: (use `python -V`)  2.7.12
PokemonGo-Map startup command: Click on shortcut
PokeAlarm startup command: `C:\Users\saics\PokeAlarm>c:\Python27\python.exe runwebhook.py`

Did the issue persist after restarting the script?: yes

## Console Output

```
C:\Users\saics\PokeAlarm>c:\Python27\python.exe runwebhook.py
2016-09-21 23:05:14,497 [     alarm_manager] [   INFO] You will be notified of t
he following pokemon:
2016-09-21 23:05:14,497 [     alarm_manager] [   INFO] Bulbasaur (Unl), Pidgey (
Unl), Rattata (Unl), Sandshrew (Unl),
2016-09-21 23:05:14,499 [     alarm_manager] [   INFO] Paras (Unl), Meowth (Unl)
, Mankey (Unl)
2016-09-21 23:05:14,499 [     alarm_manager] [   INFO] Alarm not activated: boxc
ar because value not set to "True"
2016-09-21 23:05:14,500 [     alarm_manager] [   INFO] Alarm not activated: push
bullet because value not set to "True"
2016-09-21 23:05:14,500 [     alarm_manager] [   INFO] Alarm not activated: push
over because value not set to "True"
2016-09-21 23:05:14,500 [     alarm_manager] [   INFO] Alarm not activated: slac
k because value not set to "True"
2016-09-21 23:05:14,500 [     alarm_manager] [   INFO] Alarm not activated: tele
gram because value not set to "True"
2016-09-21 23:05:14,500 [     alarm_manager] [   INFO] Alarm not activated: twil
io because value not set to "True"
2016-09-21 23:05:16,059 [             utils] [   INFO] Attempting to pip install
 twitter==1.17.1...
Traceback (most recent call last):
  File "runwebhook.py", line 93, in <module>
    alarm_thread = Alarm_Manager()
  File "C:\Users\saics\PokeAlarm\alarms\alarm_manager.py", line 66, in __init__
    from Twitter import Twitter_Alarm
  File "c:\Python27\lib\site-packages\gevent\builtins.py", line 93, in __import_
_
    result = _import(*args, **kwargs)
  File "C:\Users\saics\PokeAlarm\alarms\Twitter\__init__.py", line 9, in <module
>
    pip_install('twitter', '1.17.1')
  File "C:\Users\saics\PokeAlarm\alarms\utils.py", line 61, in pip_install
    subprocess.call(['pip', 'install', target])
  File "c:\Python27\lib\site-packages\gevent\subprocess.py", line 212, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\Python27\lib\site-packages\gevent\subprocess.py", line 534, in __init
__
    reraise(*exc_info)
  File "c:\Python27\lib\site-packages\gevent\subprocess.py", line 503, in __init
__
    restore_signals, start_new_session)
  File "c:\Python27\lib\site-packages\gevent\subprocess.py", line 847, in _execu
te_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

## Your Alarms Config

```json
{
	"alarms":[
		{
			"active":"False",
			"type":"boxcar",
			"user_credentials":"YOUR_API_KEY"
		},
		{
			"active":"False",
			"type":"pushbullet",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type":"telegram",
			"bot_token":"YOUR_BOT_TOKEN",
			"chat_id":"YOUR_CHAT_ID"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "True",
			"type": "twitter",
			"access_token": "",
			"access_secret": "",
			"consumer_key": "",
			"consumer_secret": ""
        }
	],
	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"False",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"False",
		"From_Instinct":"False"
	},
	"pokestops":{
		"Lured":"false"
	},
	"pokemon":{
		"Bulbasaur":"T",
		"Ivysaur":"False",
		"Venusaur":"False",
		"Charmander":"False",
		"Charmeleon":"False",
		"Charizard":"False",
		"Squirtle":"False",
		"Wartortle":"False",
		"Blastoise":"False",
		"Caterpie":"False",
		"Metapod":"False",
		"Butterfree":"False",
		"Weedle":"False",
		"Kakuna":"False",
		"Beedrill":"False",
		"Pidgey":"True",
		"Pidgeotto":"False",
		"Pidgeot":"False",
		"Rattata":"True",
		"Raticate":"False",
		"Spearow":"False",
		"Fearow":"False",
		"Ekans":"False",
		"Arbok":"False",
		"Pikachu":"False",
		"Raichu":"False",
		"Sandshrew":"True",
		"Sandslash":"False",
		"Nidoran♀":"False",
		"Nidorina":"False",
		"Nidoqueen":"False",
		"Nidoran♂":"False",
		"Nidorino":"False",
		"Nidoking":"False",
		"Clefairy":"False",
		"Clefable":"False",
		"Vulpix":"False",
		"Ninetales":"False",
		"Jigglypuff":"False",
		"Wigglytuff":"False",
		"Zubat":"False",
		"Golbat":"False",
		"Oddish":"False",
		"Gloom":"False",
		"Vileplume":"False",
		"Paras":"True",
		"Parasect":"False",
		"Venonat":"False",
		"Venomoth":"False",
		"Diglett":"False",
		"Dugtrio":"False",
		"Meowth":"True",
		"Persian":"False",
		"Psyduck":"False",
		"Golduck":"False",
		"Mankey":"True",
		"Primeape":"False",
		"Growlithe":"False",
		"Arcanine":"False",
		"Poliwag":"False",
		"Poliwhirl":"False",
		"Poliwrath":"False",
		"Abra":"False",
		"Kadabra":"False",
		"Alakazam":"False",
		"Machop":"False",
		"Machoke":"False",
		"Machamp":"False",
		"Bellsprout":"False",
		"Weepinbell":"False",
		"Victreebel":"False",
		"Tentacool":"False",
		"Tentacruel":"False",
		"Geodude":"False",
		"Graveler":"False",
		"Golem":"False",
		"Ponyta":"False",
		"Rapidash":"False",
		"Slowpoke":"False",
		"Slowbro":"False",
		"Magnemite":"False",
		"Magneton":"False",
		"Farfetch'd":"False",
		"Doduo":"False",
		"Dodrio":"False",
		"Seel":"False",
		"Dewgong":"False",
		"Grimer":"False",
		"Muk":"False",
		"Shellder":"False",
		"Cloyster":"False",
		"Gastly":"False",
		"Haunter":"False",
		"Gengar":"False",
		"Onix":"False",
		"Drowzee":"False",
		"Hypno":"False",
		"Krabby":"False",
		"Kingler":"False",
		"Voltorb":"False",
		"Electrode":"False",
		"Exeggcute":"False",
		"Exeggutor":"False",
		"Cubone":"False",
		"Marowak":"False",
		"Hitmonlee":"False",
		"Hitmonchan":"False",
		"Lickitung":"False",
		"Koffing":"False",
		"Weezing":"False",
		"Rhyhorn":"False",
		"Rhydon":"False",
		"Chansey":"False",
		"Tangela":"False",
		"Kangaskhan":"False",
		"Horsea":"False",
		"Seadra":"False",
		"Goldeen":"False",
		"Seaking":"False",
		"Staryu":"False",
		"Starmie":"False",
		"Mr. Mime":"False",
		"Scyther":"False",
		"Jynx":"False",
		"Electabuzz":"False",
		"Magmar":"False",
		"Pinsir":"False",
		"Tauros":"False",
		"Magikarp":"False",
		"Gyarados":"False",
		"Lapras":"False",
		"Ditto":"False",
		"Eevee":"False",
		"Vaporeon":"False",
		"Jolteon":"False",
		"Flareon":"False",
		"Porygon":"False",
		"Omanyte":"False",
		"Omastar":"False",
		"Kabuto":"False",
		"Kabutops":"False",
		"Aerodactyl":"False",
		"Snorlax":"False",
		"Articuno":"False",
		"Zapdos":"False",
		"Moltres":"False",
		"Dratini":"False",
		"Dragonair":"False",
		"Dragonite":"False",
		"Mewtwo":"False",
		"Mew":"False"
	}
}

```

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Hi @saics72. Can you try opening an admin command prompt and typing `pip install twitter` and see if that fixes your problem?

**Comment by kvangent** [comment]
@saics72 Did you get your problem figured out? If we don't hear back from you in the next 24-48hours I will assume your problem is fixed and close out this issue.

**Comment by saics72** [comment]
Hi Kvangent,

Yes, it was due to path problem.  After adding the right paths, it works!  Thanks so much for the excellent support.  

Regards,
Thang
