### ISSUE TITLE
[BUG?] Parse_Mode HTML

### ISSUE THREAD

**Issue by roflinger** [kvangent/PokeAlarm#246]
## Problem Description

In the telegram_alarms.py there is parse mode on option HTML
When I edit it in the alarms.json like:
"body": "<gmaps> <a href="http://www.example.com/">inline URL</a> \n Verfügbar bis <24h_time> (<time_left>)."

it doesn´t accept the <a href="http://www.example.com/">inline URL</a>
Why?

## Your Environment

Operating System:  win 10 64bit
Python Version: (use `python -V`)  2.7
PokemonGo-Map startup command: too long :)
PokeAlarm startup command: `python runwebhook.py -L de`

Did the issue persist after restarting the script?: yes/no
yes

## Console Output

```
	<C:\a\PokeAlarm>python runwebhook.py -L de
Traceback (most recent call last):
  File "runwebhook.py", line 93, in <module>
    alarm_thread = Alarm_Manager()
  File "C:\a\PokeAlarm\alarms\alarm_manager.py", line 26, in __init__
    settings = json.load(file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 31 column 31 (char 654)>
```

## Your Alarms Config

```json
    <{
	"alarms":[
		{
			"active":"False",
			"type":"boxcar",
			"user_credentials":"YOUR_API_KEY"
		},
		{
			"active":"False",
			"type":"pushbullet",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "True",
			"type":"telegram",
			"bot_token":removedkeys
			"chat_id":"-removedkeys
			"pokemon" : {
				"title": "Ein wildes <pkmn> ist aufgetaucht! \n(IV:<iv>)\nAttacken:<move1>/<move2>",
				"body": "<gmaps> <a href="http://www.example.com/">inline URL</a> \n Verfügbar bis <24h_time> (<time_left>)."
			},
			"pokestop":{
				"title":"Someone has placed a lure on a Pokestop!",
				"body": "<gmaps> \n Lure will expire at <24h_time> (<time_left>)."
			},
			"gym":{
				"title":"A Team <old_team> gym has fallen!",
				"body": "<gmaps> \n It is now controlled by <new_team>."
			}
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "False",
			"type": "twitter",
			"access_token": twitterblaremovedtokens
			"access_secret":twitterblaremovedtokens
			"consumer_key": twitterblaremovedtokens
			"consumer_secrettwitterblaremovedtokens
        }
	],
	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"False",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"False",
		"From_Instinct":"False"
	},
	"pokestops":{
		"Lured":"False"
	},
	"pokemon":{
		"max_dist":"inf",
		"min_iv":"0",
		"__comment" : "Bisasam",
		"Bulbasaur":"True",
		"__comment" : "Bisaknosp",
		"Ivysaur":"True",
		"__comment" : "Bisaflor",
		"Venusaur":"True",
		"__comment" : "Glumanda",
		"Charmander":"True",
		"__comment" : "Glutexo",
		"Charmeleon":"True",
		"__comment" : "Glurak",
		"Charizard":"True",
		"__comment" : "Schiggy",
		"Squirtle":"True",
		"__comment" : "Schillok",
		"Wartortle":"True",
		"__comment" : "Turtok",
		"Blastoise":"True",
		"__comment" : "Raupy",
		"Caterpie":"False",
		"__comment" : "Safcon",
		"Metapod":"False",
		"__comment" : "Smettbo",
		"Butterfree":"False",
		"__comment" : "Hornliu",
		"Weedle":"False",
		"__comment" : "Kokuna",
		"Kakuna":"False",
		"__comment" : "Bibor",
		"Beedrill":"False",
		"__comment" : "Taubsi",
		"Taubsi":"True",
		"__comment" : "Tauboga",
		"Pidgeotto":"False",
		"__comment" : "Tauboss",
		"Pidgeot":"False",
		"__comment" : "Rattfratz",
		"Rattata":"False",
		"__comment" : "Rattikarl",
		"Raticate":"False",
		"__comment" : "Habitak",
		"Spearow":"False",
		"__comment" : "Ibitak",
		"Fearow":"False",
		"__comment" : "Rettan",
		"Ekans":"True",
		"__comment" : "Arbok",
		"Arbok":"True",
		"__comment" : "Pikachu",
		"Pikachu":"True",
		"__comment" : "Raichu",
		"Raichu":"True",
		"__comment" : "Sandan",
		"Sandshrew":"True",
		"__comment" : "Sandamer",
		"Sandslash":"True",
		"__comment" : "Nidoran♀",
		"Nidoran♀":"False",
		"__comment" : "Nidorina",
		"Nidorina":"False",
		"__comment" : "Nidoqueen",
		"Nidoqueen":"False",
		"__comment" : "Nidoran♂",
		"Nidoran♂":"False",
		"__comment" : "Nidorino",
		"Nidorino":"False",
		"__comment" : "Nidoking",
		"Nidoking":"True",
		"__comment" : "Piepi",
		"Clefairy":"False",
		"__comment" : "Pixi",
		"Clefable":"False",
		"__comment" : "Vulpix",
		"Vulpix":"True",
		"__comment" : "Vulnona",
		"Ninetales":"True",
		"__comment" : "Pummeluff",
		"Jigglypuff":"False",
		"__comment" : "Knuddeluff",
		"Wigglytuff":"False",
		"__comment" : "Zubat",
		"Zubat":"False",
		"__comment" : "Golbat",
		"Golbat":"False",
		"__comment" : "Myrapla",
		"Oddish":"False",
		"__comment" : "Duflor",
		"Gloom":"False",
		"__comment" : "Giflor",
		"Vileplume":"True",
		"__comment" : "Paras",
		"Paras":"False",
		"__comment" : "Parasek",
		"Parasect":"False",
		"__comment" : "Bluzuk",
		"Venonat":"False",
		"__comment" : "Omot",
		"Venomoth":"False",
		"__comment" : "Digda",
		"Diglett":"True",
		"__comment" : "Digdri",
		"Dugtrio":"False",
		"__comment" : "Mauzi",
		"Meowth":"False",
		"__comment" : "Snobilikat",
		"Persian":"True",
		"__comment" : "Enton",
		"Psyduck":"False",
		"__comment" : "Entoron",
		"Golduck":"False",
		"__comment" : "Menki",
		"Mankey":"False",
		"__comment" : "Rasaff",
		"Primeape":"True",
		"__comment" : "Fukano",
		"Growlithe":"True",
		"__comment" : "Arkani",
		"Arcanine":"True",
		"__comment" : "Quapsel",
		"Poliwag":"False",
		"__comment" : "Quaputzi",
		"Poliwhirl":"False",
		"__comment" : "Quappo",
		"Poliwrath":"False",
		"__comment" : "Abra",
		"Abra":"True",
		"__comment" : "Kadabra",
		"Kadabra":"True",
		"__comment" : "Simsala",
		"Alakazam":"True",
		"__comment" : "Machollo",
		"Machop":"True",
		"__comment" : "Maschock",
		"Machoke":"True",
		"__comment" : "Machomei",
		"Machamp":"True",
		"__comment" : "Knofensa",
		"Bellsprout":"False",
		"__comment" : "Ultrigaria",
		"Weepinbell":"False",
		"__comment" : "Sarzenia",
		"Victreebel":"True",
		"__comment" : "Tentacha",
		"Tentacool":"False",
		"__comment" : "Tentoxa",
		"Tentacruel":"True",
		"__comment" : "Kleinstein",
		"Geodude":"True",
		"__comment" : "Georok",
		"Graveler":"True",
		"__comment" : "Geowaz",
		"Golem":"True",
		"__comment" : "Ponita",
		"Ponyta":"True",
		"__comment" : "Gallopa",
		"Rapidash":"False",
		"__comment" : "Flegmon",
		"Slowpoke":"False",
		"__comment" : "Lahmus",
		"Slowbro":"True",
		"__comment" : "Magnetilo",
		"Magnemite":"True",
		"__comment" : "Magneton",
		"Magneton":"True",
		"__comment" : "Porenta",
		"Farfetch'd":"True",
		"__comment" : "Dodu",
		"Doduo":"True",
		"__comment" : "Dodri",
		"Dodrio":"True",
		"__comment" : "Jurob",
		"Seel":"False",
		"__comment" : "Jugong",
		"Dewgong":"True",
		"__comment" : "Sleima",
		"Grimer":"True",
		"__comment" : "Sleimok",
		"Muk":"True",
		"__comment" : "Muschas",
		"Shellder":"False",
		"__comment" : "Austos",
		"Cloyster":"True",
		"__comment" : "Nebulak",
		"Gastly":"False",
		"__comment" : "Alpollo",
		"Haunter":"True",
		"__comment" : "Gengar",
		"Gengar":"True",
		"__comment" : "Onix",
		"Onix":"True",
		"__comment" : "Traumato",
		"Drowzee":"False",
		"__comment" : "Hypno",
		"Hypno":"False",
		"__comment" : "Krabby",
		"Krabby":"False",
		"__comment" : "Kingler",
		"Kingler":"False",
		"__comment" : "Voltobal",
		"Voltorb":"True",
		"__comment" : "Lektrobal",
		"Electrode":"True",
		"__comment" : "Owei",
		"Exeggcute":"True",
		"__comment" : "Kokowei",
		"Exeggutor":"True",
		"__comment" : "Tragosso",
		"Cubone":"True",
		"__comment" : "Knogga",
		"Marowak":"True",
		"__comment" : "Kicklee",
		"Hitmonlee":"True",
		"__comment" : "Nockchan",
		"Hitmonchan":"True",
		"__comment" : "Schlurp",
		"Lickitung":"True",
		"__comment" : "Smogon",
		"Koffing":"True",
		"__comment" : "Smogmog",
		"Weezing":"True",
		"__comment" : "Rihorn",
		"Rhyhorn":"True",
		"__comment" : "Rizeros",
		"Rhydon":"True",
		"__comment" : "Chaneira",
		"Chansey":"True",
		"__comment" : "Tangela",
		"Tangela":"True",
		"__comment" : "Kangama",
		"Kangaskhan":"False",
		"__comment" : "Seeper",
		"Horsea":"False",
		"__comment" : "Seemon",
		"Seadra":"True",
		"__comment" : "Goldini",
		"Goldeen":"False",
		"__comment" : "Golking",
		"Seaking":"False",
		"__comment" : "Sterndu",
		"Staryu":"False",
		"__comment" : "Starmie",
		"Starmie":"False",
		"__comment" : "Pantimos",
		"Mr. Mime":"False",
		"__comment" : "Sichlor",
		"Scyther":"True",
		"__comment" : "Rossana",
		"Jynx":"False",
		"__comment" : "Elektek",
		"Electabuzz":"True",
		"__comment" : "Magmar",
		"Magmar":"True",
		"__comment" : "Pinsir",
		"Pinsir":"True",
		"__comment" : "Tauros",
		"Tauros":"True",
		"__comment" : "Karpador",
		"Magikarp":"False",
		"__comment" : "Garados",
		"Gyarados":"True",
		"__comment" : "Lapras",
		"Lapras":"True",
		"__comment" : "Ditto",
		"Ditto":"True",
		"__comment" : "Evoli",
		"Eevee":"False",
		"__comment" : "Aquana",
		"Vaporeon":"True",
		"__comment" : "Blitza",
		"Jolteon":"True",
		"__comment" : "Flamara",
		"Flareon":"True",
		"__comment" : "Porygon",
		"Porygon":"True",
		"__comment" : "Amonitas",
		"Omanyte":"True",
		"__comment" : "Amoroso",
		"Omastar":"True",
		"__comment" : "Kabuto",
		"Kabuto":"True",
		"__comment" : "Kabutops",
		"Kabutops":"True",
		"__comment" : "Aerodactyl",
		"Aerodactyl":"True",
		"__comment" : "Relaxo",
		"Snorlax":"True",
		"__comment" : "Arktos",
		"Articuno":"True",
		"__comment" : "Zapdos",
		"Zapdos":"True",
		"__comment" : "Lavados",
		"Moltres":"True",
		"__comment" : "Dratini",
		"Dratini":"True",
		"__comment" : "Dragonir",
		"Dragonair":"True",
		"__comment" : "Dragoran",
		"Dragonite":"True",
		"__comment" : "Mewtu",
		"Mewtwo":"True",
		"__comment" : "Mew",
		"Mew":"True"
	}
}

>
```

## Troubleshooting Checklist
[ x] Most recent version of PokemonGo-Map
[ x] Most recent version of PokeAlarm
[ x] Checked the Wiki page for service in question

## Enhancement Description

---

## Use cases

right at the start

**Comment by kvangent** [comment]
You need to escape your quotes most likely so it can be read is JSON format:  
```json
"body":"<a href=\"http://www.example.com/\">inline URL</a>"
```

Not saying that you are, but if you are planning to put a donate link in there (something we've seen beore) you should know two things: 
1. It's violation of the GNU licensing agreement which states `you must pass on to the recipients the same
freedoms that you received`. This means that if you haven't payed for it, you can't ask others to pay for it.
2. It's a shitty thing to do. I've put hundreds of hours into this project and make it avaible for free, and think it's pretty lame for other people to try and make money from it.

**Comment by roflinger** [comment]
haha no i am not planning to do this ^^ 
i wanna have the gmaps as an inline "route" like 

'"body":"<a href=\"<gmaps>\">route</a>"

if it is possible

**Comment by kvangent** [comment]
That works.
