### ISSUE TITLE
[BUG/USER SPECIFIC] Problem with SSL error (Gmaps?)

### ISSUE THREAD

**Issue by joachimvenaas** [kvangent/PokeAlarm#258]
## Problem Description

I updated both my pokemongo-map and pokealarm today, pokemongo-map is working flawlessly. But pokealarm gets the following error when it find pokemons to notificate me about (slack).

## Your Environment

Operating System:  Windows 8.1
Python Version: 2.7.9
PokemonGo-Map startup command: runserver.py -cf config/config.ini
PokeAlarm startup command: config file with gmaps api key with debug mode

Did the issue persist after restarting the script?: yes

## Console Output

```
2016-10-03 21:36:41,707 [     alarm_manager] [   INFO] Eevee notication was triggered!
2016-10-03 21:36:41,707 [    connectionpool] [   INFO] Starting new HTTPS connection (1): maps.googleapis.com
2016-10-03 21:36:41,811 [     alarm_manager] [  ERROR] Error while processing request: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
2016-10-03 21:36:41,811 [     alarm_manager] [  DEBUG] Stack trace:
 Traceback (most recent call last):
  File "C:\PokeAlarm\alarms\alarm_manager.py", line 125, in run
    self.trigger_pokemon(data['message'])
  File "C:\PokeAlarm\alarms\alarm_manager.py", line 232, in trigger_pokemon
    pkmn_info = self.optional_arguments(pkmn_info)
  File "C:\PokeAlarm\alarms\alarm_manager.py", line 363, in optional_arguments
    info.update(**reverse_location(info))
  File "C:\PokeAlarm\alarms\utils.py", line 340, in reverse_location
    result = config['GMAPS_CLIENT'].reverse_geocode((lat,lng))[0]
  File "C:\Python27\lib\site-packages\googlemaps\geocoding.py", line 109, in reverse_geocode
    return client._get("/maps/api/geocode/json", params)["results"]
  File "C:\Python27\lib\site-packages\googlemaps\client.py", line 222, in _get
    raise googlemaps.exceptions.TransportError(e)
TransportError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

2016-10-03 21:36:41,811 [     alarm_manager] [  DEBUG] Request format:
 {
    "message": {
        "disappear_time": 1475524186,
        "encounter_id": "MzE4MDg0ODAzNTc4Nzk3MzkzMw==",
        "individual_attack": 9,
        "individual_defense": 15,
        "individual_stamina": 11,
        "last_modified_time": 1475523405902,
        "latitude": 62.742989102792464,
        "longitude": 7.160886847193396,
        "move_1": 221,
        "move_2": 131,
        "pokemon_id": 133,
        "spawnpoint_id": "461156a666f",
        "time_until_hidden_ms": 780494
    },
    "type": "pokemon"
}
```

## Your Alarms Config

```json
{
	"alarms":[
		{
			"active":"False",
			"type":"boxcar",
			"user_credentials":"YOUR_API_KEY"
		},
		{
			"active":"False",
			"type":"pushbullet",
			"api_key":"YOUR_API_KEY"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		},
		{
			"active": "True",
			"type":"slack",
			"api_key":"SLACKAPIKEY",
			"startup_list": "false",
			"startup_message": "false",
			"pokemon": {
				"channel": "general",
				"username": "<pkmn>",
				"icon_url": "https://raw.githubusercontent.com/kvangent/PokeAlarm/master/icons/<id>.png",
				"title": "<pkmn> has appeared!",
				"url": "<gmaps>",
				"body": "<address> until <24h_time> (<time_left>). <iv>% (<atk> <def> <sta>): <move1> & <move2>",
				"map": {             
					"enabled": "true", 
					"width": "500",    
					"height": "250",  
					"maptype": "roadmap",
					"zoom": "15"      
				}                      
			}
		},
		{
			"active": "False",
			"type":"telegram",
			"bot_token":"YOUR_BOT_TOKEN",
			"chat_id":"YOUR_CHAT_ID"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "False",
			"type": "twitter",
			"access_token": "YOUR_ACCESS_TOKEN",
			"access_secret": "YOUR_ACCESS_SECRET",
			"consumer_key": "YOUR_CONSUMER_KEY",
			"consumer_secret": "YOUR_CONSUMER_SECRET"
        }
	],
	"gyms":{
		"To_Valor":"False",
		"To_Mystic":"False",
		"To_Instinct":"False",
		"From_Valor":"False",
		"From_Mystic":"False",
		"From_Instinct":"False"
	},
	"pokestops":{
		"Lured":"False"
	},
	"pokemon":{
		"max_dist":"inf",
		"min_iv":"0",
		"Bulbasaur":"True",
		"Ivysaur":"True",
		"Venusaur":"True",
		"Charmander":"True",
		"Charmeleon":"True",
		"Charizard":"True",
		"Squirtle":{ "max_dist":"inf", "min_iv":"90", "move_1":"all", "move_2":"all" },
		"Wartortle":"True",
               .......
		"Dragonite":"True",
		"Mewtwo":"True",
		"Mew":"True"
	}
}


```

## Troubleshooting Checklist
[x] Most recent version of PokemonGo-Map
[x] Most recent version of PokeAlarm
[x] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Could you try the following `pip uninstall -y certifi && pip install certifi==2015.04.28`

**Comment by joachimvenaas** [comment]
That worked! thanks!
