### ISSUE TITLE
Problem running python runwebhook.py

### ISSUE THREAD

**Issue by Varnsen** [kvangent/PokeAlarm#29]
Hey guys, just attempted to set this up for my Telegram bot, running into an issue when I try to 
```
python runwebhook.py
root@server-1:/home/admin/PokeAlarm# python runwebhook.py -H IPHERE -P PORTHERE
Traceback (most recent call last):
  File "runwebhook.py", line 2, in <module>
    from gevent import monkey; monkey.patch_all()
  File "/usr/local/lib/python2.7/dist-packages/gevent/__init__.py", line 49, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 11, in <module>
    from greenlet import greenlet, getcurrent, GreenletExit
ImportError: /usr/local/lib/python2.7/dist-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
```

Any idea what could be causing this? Running pip install -r requirements.txt seems to confirm all requirements are met.

**Comment by FritzSG** [comment]
I also get the same thing:
`
python runwebhook.py -h 127.0.0.1 -p 4000
Traceback (most recent call last):
  File "runwebhook.py", line 2, in <module>
    from gevent import monkey; monkey.patch_all()
  File "C:\Python27\lib\site-packages\gevent\__init__.py", line 49, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 11, in <module>
    from greenlet import greenlet, getcurrent, GreenletExit
ImportError: DLL load failed: The specified procedure could not be found.`

**Comment by FritzSG** [comment]
I had to install the latest patch for python to fix this. Now running 2.7.11 and it works.

**Comment by kvangent** [comment]
@Varnsen Could you update python and run pip install -r requirements again?

**Comment by kvangent** [comment]
A few people have solve issues by updating pip. Try `pip install --upgrade setuptools` and then reinstall the requirements.

**Comment by Varnsen** [comment]
I just tried running setuptools, this was my response:

```
ImportError: /usr/local/lib/python2.7/dist-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
root@server-1:/home/admin/PokeAlarm# pip install --upgrade setuptools
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting setuptools
  Downloading setuptools-25.1.3-py2.py3-none-any.whl (442kB)
    100% |████████████████████████████████| 450kB 663kB/s
Installing collected packages: setuptools
  Found existing installation: setuptools 25.1.1
    Uninstalling setuptools-25.1.1:
      Successfully uninstalled setuptools-25.1.1
Successfully installed setuptools-25.1.3
root@server-1:/home/admin/PokeAlarm# python runwebhook.py -H IP -P PORT
Traceback (most recent call last):
  File "runwebhook.py", line 2, in <module>
    from gevent import monkey; monkey.patch_all()
  File "/usr/local/lib/python2.7/dist-packages/gevent/__init__.py", line 49, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 11, in <module>
    from greenlet import greenlet, getcurrent, GreenletExit
ImportError: /usr/local/lib/python2.7/dist-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object

```

I checked my Python version, which I'm guessing is the problem if @FritzSG was able to fix it, and it looks like:

```
root@server-1:/home/admin/PokeAlarm# python -V
Python 2.7.3
root@server-1:/home/admin/PokeAlarm#
```

My friend who owns the server we're working on isn't comfortable with me updating on my own (no trust!), so when he's home in a few hours we're going to try to update to 2.7.11 and hopefully that'll fix the problem. I'll keep you posted.

**Comment by kvangent** [comment]
I'm going to close this issue for now. If you continue to have problems after the API is fixed, please reopen.

**Comment by Varnsen** [comment]
Hey, sorry to reopen this ticket again (if this comment does reopen). I'm trying to take things into my own hands as the guy who usually does these changes isn't up for messing around with the Python upgrade.

I followed **[this tutorial](http://mbless.de/blog/2016/01/09/upgrade-to-python-2711-on-ubuntu-1404-lts.html)**, which is all I could find on upgrading to python 2.7.11. So, right now PokeAlarm is running on a virtualenv which appears to be 2.7.11

```
(venv) root@server-1:/home/ubuntu/PKM/PokeAlarm# python -V
Python 2.7.11
(venv) root@server-1:/home/ubuntu/PKM/PokeAlarm#
```

This probably isn't ideal, but I have no clue how to properly install 2.7.11 over 2.7.3 ([Here's my stackoverflow question on the matter](http://stackoverflow.com/questions/38817941/problems-upgrading-python-2-7-3-to-2-7-11-on-server-running-ubuntu-12-04))

After running requirements.txt again (slightly different command to get it working)
I get this result:

```
(venv) root@server-1:/home/ubuntu/PKM/PokeAlarm# pip install -r ./requirements.txt

Collecting Flask==0.11.1 (from -r ./requirements.txt (line 1))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting configargparse==0.10.0 (from -r ./requirements.txt (line 2))
  Using cached ConfigArgParse-0.10.0.tar.gz
Collecting pushbullet.py==0.10.0 (from -r ./requirements.txt (line 3))
  Using cached pushbullet.py-0.10.0-py2.py3-none-any.whl
Collecting slacker==0.9.24 (from -r ./requirements.txt (line 4))
  Using cached slacker-0.9.24.tar.gz
Collecting twilio==5.4.0 (from -r ./requirements.txt (line 5))
  Using cached twilio-5.4.0.tar.gz
Collecting telepot==8.3 (from -r ./requirements.txt (line 6))
  Using cached telepot-8.3.zip
Collecting gevent==1.1.2 (from -r ./requirements.txt (line 7))
  Downloading gevent-1.1.2-cp27-cp27m-manylinux1_x86_64.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 691kB/s
Collecting geocoder==1.15.1 (from -r ./requirements.txt (line 8))
  Using cached geocoder-1.15.1-py2.py3-none-any.whl
Collecting click>=2.0 (from Flask==0.11.1->-r ./requirements.txt (line 1))
  Using cached click-6.6.tar.gz
Collecting Werkzeug>=0.7 (from Flask==0.11.1->-r ./requirements.txt (line 1))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from Flask==0.11.1->-r ./requirements.txt (line 1))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from Flask==0.11.1->-r ./requirements.txt (line 1))
  Using cached itsdangerous-0.24.tar.gz
Collecting python-magic (from pushbullet.py==0.10.0->-r ./requirements.txt (line 3))
  Using cached python-magic-0.4.12.tar.gz
Collecting websocket-client (from pushbullet.py==0.10.0->-r ./requirements.txt (line 3))
  Using cached websocket_client-0.37.0.tar.gz
Collecting requests>=1.0.0 (from pushbullet.py==0.10.0->-r ./requirements.txt (line 3))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting httplib2>=0.7 (from twilio==5.4.0->-r ./requirements.txt (line 5))
  Downloading httplib2-0.9.2.zip (210kB)
    100% |████████████████████████████████| 215kB 3.7MB/s
Collecting six (from twilio==5.4.0->-r ./requirements.txt (line 5))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pytz (from twilio==5.4.0->-r ./requirements.txt (line 5))
  Using cached pytz-2016.6.1-py2.py3-none-any.whl
Collecting urllib3==1.9.1 (from telepot==8.3->-r ./requirements.txt (line 6))
  Using cached urllib3-1.9.1-py2-none-any.whl
Collecting greenlet>=0.4.9 (from gevent==1.1.2->-r ./requirements.txt (line 7))
  Downloading greenlet-0.4.10-cp27-cp27m-manylinux1_x86_64.whl (41kB)
    100% |████████████████████████████████| 51kB 13.0MB/s
Collecting ratelim (from geocoder==1.15.1->-r ./requirements.txt (line 8))
  Using cached ratelim-0.1.6-py2.py3-none-any.whl
Collecting MarkupSafe (from Jinja2>=2.4->Flask==0.11.1->-r ./requirements.txt (line 1))
  Using cached MarkupSafe-0.23.tar.gz
Collecting decorator (from ratelim->geocoder==1.15.1->-r ./requirements.txt (line 8))
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Building wheels for collected packages: configargparse, slacker, twilio, telepot, click, itsdangerous, pyth                                               on-magic, websocket-client, httplib2, MarkupSafe
  Running setup.py bdist_wheel for configargparse ... done
  Stored in directory: /root/.cache/pip/wheels/1e/2a/b6/4a95a72c4f9caf9d2a8873487ea7a65f7e46a1133a75df9856
  Running setup.py bdist_wheel for slacker ... done
  Stored in directory: /root/.cache/pip/wheels/64/51/2f/52ac4cd221b9e8ca1b6f4b302732b709b5a76f11272fef1935
  Running setup.py bdist_wheel for twilio ... done
  Stored in directory: /root/.cache/pip/wheels/91/16/85/2ea21326cf1aad3e32f88d9e81723088e1e43ceb9eac935a9b
  Running setup.py bdist_wheel for telepot ... done
  Stored in directory: /root/.cache/pip/wheels/2d/e6/30/047a8e2a034f26785554d6ca79f791795da9cf0e54d02de4cc
  Running setup.py bdist_wheel for click ... done
  Stored in directory: /root/.cache/pip/wheels/b0/6d/8c/cf5ca1146e48bc7914748bfb1dbf3a40a440b8b4f4f0d952dd
  Running setup.py bdist_wheel for itsdangerous ... done
  Stored in directory: /root/.cache/pip/wheels/fc/a8/66/24d655233c757e178d45dea2de22a04c6d92766abfb741129a
  Running setup.py bdist_wheel for python-magic ... done
  Stored in directory: /root/.cache/pip/wheels/f8/61/e5/dd1029e23a94a40b995eab1a9e06a1cf874c7745a383af5034
  Running setup.py bdist_wheel for websocket-client ... done
  Stored in directory: /root/.cache/pip/wheels/e4/20/12/48d6732b88733a0a8f98ee1a5b2f59b64b27011d5c34c4f98c
  Running setup.py bdist_wheel for httplib2 ... done
  Stored in directory: /root/.cache/pip/wheels/c7/67/60/e0be8ccfc1e08f8ff1f50d99ea5378e204580ea77b0169fb55
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /root/.cache/pip/wheels/a3/fa/dc/0198eed9ad95489b8a4f45d14dd5d2aee3f8984e46862c5748
Successfully built configargparse slacker twilio telepot click itsdangerous python-magic websocket-client h                                               ttplib2 MarkupSafe
Installing collected packages: click, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, configargparse, py                                               thon-magic, six, websocket-client, requests, pushbullet.py, slacker, httplib2, pytz, twilio, urllib3, telep                                               ot, greenlet, gevent, decorator, ratelim, geocoder
Successfully installed Flask-0.11.1 Jinja2-2.8 MarkupSafe-0.23 Werkzeug-0.11.10 click-6.6 configargparse-0.                                               10.0 decorator-4.0.10 geocoder-1.15.1 gevent-1.1.2 greenlet-0.4.10 httplib2-0.9.2 itsdangerous-0.24 pushbul                                               let.py-0.10.0 python-magic-0.4.12 pytz-2016.6.1 ratelim-0.1.6 requests-2.10.0 six-1.10.0 slacker-0.9.24 tel                                               epot-8.3 twilio-5.4.0 urllib3-1.9.1 websocket-client-0.37.0
(venv) root@server-1:/home/ubuntu/PKM/PokeAlarm#
```
Which seems like the result we're hoping for, I think? As far as my limited knowledge goes.

When I then run:
`(venv) root@server-1:/home/ubuntu/PKM/PokeAlarm# python runwebhook.py`
I get the following errors:
```
(venv) root@server-1:/home/ubuntu/PKM/PokeAlarm# python runwebhook.py
Traceback (most recent call last):
  File "runwebhook.py", line 54, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "/home/ubuntu/PKM/PokeAlarm/alarms/alarm_manager.py", line 28, in __init__
    settings = json.load(file)
  File "/usr/local/lib/python2.7.11/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/lib/python2.7.11/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7.11/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7.11/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 27 column 5 (char 500)
(venv) root@server-1:/home/ubuntu/PKM/PokeAlarm# python -V
Python 2.7.11
```

Any ideas? Sorry about this - I know I'm a novice, I wish my server bud would actually help me out with a proper 2.7.11 installation.

**Comment by kvangent** [comment]
Your problem now looks like a JSON error. Run your alarms configuration through a json formatter. Looks like a missing comma at the end of like 26.

-------- Original message --------

**Comment by Varnsen** [comment]
Ahhhh success! Thank you so much. The problem on the last bit, was since I added the notify_text value, I needed to add a comma to the end of my telegram bot_token. Everything seems to be good on this issue with the virtualenv.

```
2016-08-07 20:34:06,472 [     alarm_manager] [   INFO] Alarm not activated: pushbullet because value not set to "True"
2016-08-07 20:34:06,472 [     alarm_manager] [   INFO] Alarm not activated: slack because value not set to "True"
2016-08-07 20:34:06,472 [     alarm_manager] [   INFO] Alarm not activated: twilio because value not set to "True"
2016-08-07 20:34:06,472 [    telegram_alarm] [   INFO] Telegram Alarm intialized
2016-08-07 20:34:06,473 [    connectionpool] [   INFO] Starting new HTTPS connection (1): api.telegram.org
2016-08-07 20:34:06,557 [     alarm_manager] [   INFO] PokeAlarm has started! Your alarms should trigger now.
2016-08-07 20:34:06,558 [        runwebhook] [   INFO] Webhook server running on http://127.0.0.1:4000
```

**Comment by kvangent** [comment]
Awesome, glad you got it working.




-------- Original message --------
