### ISSUE TITLE
Error running latest Update With PokemonGo-Map Dev Branch

### ISSUE THREAD

**Issue by Aidz24** [kvangent/PokeAlarm#34]
Trying to re-setup my PokeAlarm (which was working brilliantly!). I downloaded PokemonGO-Map latest dev build and I cannot for the life of me get it to work. I've tried to change alarms, looking at possible changes I made from the first time, and nothing yet.

Here's what I'm getting.

C:\Users\Copmputer\Desktop\PokeTools\PokeAlarm-master>C:\Python27\python runwebhook.py
Traceback (most recent call last):
  File "runwebhook.py", line 51, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "C:\Users\Computer\Desktop\PokeTools\PokeAlarm-master\alarms\alarm_manager.py", line 23, in __init__
    settings = json.load(file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 7 column 4 (char 116)

**Comment by kvangent** [comment]
Add a comma after the api_key parameter.

**Comment by Aidz24** [comment]
Added a coma after the pushbullet api_key parameter, however still getting almost identical errors.

I changed

"api_key":"Pushbullet-API-Here"

to

"api_key":"Pushbullet-API-Here", 

C:\Users\Computer\Desktop\PokeTools\PokeAlarm-master>C:\python27\python runwebhook.py
Traceback (most recent call last):
  File "runwebhook.py", line 51, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "C:\Users\Computer\Desktop\PokeTools\PokeAlarm-master\alarms\alarm_manager.py", line 23, in __init__
    settings = json.load(file)
  File "C:\python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 7 column 3 (char 116)

**Comment by kvangent** [comment]
Can you post your Alarm.json? The alarms portion?

**Comment by Aidz24** [comment]
I'm using both Slack and Pushbullet (Maybe thats the problem?)

{
	"alarms":[
		{
			"active": "True",
			"type":"pushbullet",
			"api_key":"Pushbullet-API-Here",
		},
		{
			"active": "True",
			"type":"slack",
			"api_key":"Slack-API-Here",
			"channel":"#pokemap"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"",
			"auth_token":"",
			"to_number":"+11234567890",
			"from_number":"+11234567890"
		}
	],

**Comment by kvangent** [comment]
Ok so now you got rid of the channel field, so you need to remove the comma. JSON format requires a comma between every item, but not at the end.
