### ISSUE TITLE
[User Specific] ValueError: Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by myntath** [kvangent/PokeAlarm#347]
## Problem Description
PokeAlarm can't format 'iv' because it is a string and not an float/int.

## Your Environment
!--- Please post as many details  --
Operating System  Linux
Python Version (use `python -V`)  2.7
PokeAlarm startup command `cmd` : python start_pokealarm.py

the issue persists after restarting the script

## Console Output
2017-03-15 10:56:51,049 [        "pokes"][   Manager][   ERROR] Encountered error during processing: ValueError: Unknown format code 'f' for object of type 'str'
2017-03-15 10:56:51,049 [        "pokes"][   Manager][   ERROR] Stack trace:
 Traceback (most recent call last):
  File "/home/mynt/PokeAlarm/PokeAlarm/Manager.py", line 286, in run
    self.process_pokemon(obj)
  File "/home/mynt/PokeAlarm/PokeAlarm/Manager.py", line 370, in process_pokemon
    name, iv, filt.min_iv, filt.max_iv, filt_ct))
ValueError: Unknown format code 'f' for object of type 'str'

(the change in stacktrace debug level is mine)

## Your Alarms Config

N/A

## Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokeAlarm
[X] Checked the Wiki page for service in question

**Comment by kvangent** [comment]
Please make sure you are on the most recent commit and that you haven't changed any files. Your line numbers are different than the main commit at the moment.

**Comment by kvangent** [comment]
I haven't heard anything back, so I'm assuming the error was fixed. Please let me know if not.
