### ISSUE TITLE
Crash sometimes when Notification Triggered

### ISSUE THREAD

**Issue by warxhead1** [kvangent/PokeAlarm#36]
2016-08-07 05:08:56,487 [     alarm_manager] [   INFO] Pikachu notication was triggered!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/warxhead/PokeAlarm/alarms/alarm_manager.py", line 63, in run
    self.trigger_pkmn(data['message'])
  File "/home/warxhead/PokeAlarm/alarms/alarm_manager.py", line 108, in trigger_pkmn
    'addr': get_address(lat, lng),
  File "/home/warxhead/PokeAlarm/alarms/utils.py", line 93, in get_address
    return loc.housenumber + " " + loc.street
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

I get the same crash in windows too

**Comment by vervsdvgwegfeg** [comment]
me to:
`2016-08-07 13:05:38,601 [     alarm_manager] [   INFO] Slowpoke notication was triggered!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\Test\Desktop\Pokemon\PokemonGo-Map\alarms\alarm_manager.py", line 63, in run
    self.trigger_pkmn(data['message'])
  File "C:\Users\Test\Desktop\Pokemon\PokemonGo-Map\alarms\alarm_manager.py", line 108, in trigger_pkmn
    'addr': get_address(lat, lng),
  File "C:\Users\Test\Desktop\Pokemon\PokemonGo-Map\alarms\utils.py", line 93, in get_address
    return loc.housenumber + " " + loc.street
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

**Comment by Maerchensarg** [comment]
This is what I get:

2016-08-07 13:54:53,773 [     alarm_manager] [   INFO] Alarm not activated: pushbullet because value not set to "True"
2016-08-07 13:54:53,773 [     alarm_manager] [   INFO] Alarm not activated: slack because value not set to "True"
2016-08-07 13:54:53,773 [     alarm_manager] [   INFO] Alarm not activated: twilio because value not set to "True"
2016-08-07 13:54:53,773 [    telegram_alarm] [   INFO] Telegram Alarm intialized
2016-08-07 13:54:53,773 [    connectionpool] [   INFO] Starting new HTTPS connection (1): api.telegram.org
2016-08-07 13:54:54,382 [     alarm_manager] [   INFO] PokeAlarm has started! Your alarms should trigger now.
2016-08-07 13:54:54,382 [        runwebhook] [   INFO] Webhook server running on http://127.0.0.1:4000
2016-08-07 13:54:54,789 [     alarm_manager] [   INFO] Weedle notication was triggered!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\PGM\PokeAlarm-master\alarms\alarm_manager.py", line 63, in run
    self.trigger_pkmn(data['message'])
  File "D:\PGM\PokeAlarm-master\alarms\alarm_manager.py", line 119, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "D:\PGM\PokeAlarm-master\alarms\telegram_alarm.py", line 20, in pokemon_alert
    header = replace(self.header, pkinfo)
  File "D:\PGM\PokeAlarm-master\alarms\utils.py", line 137, in replace
    s = s.replace("<{}>".format(key), str(pkinfo[key]))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 11: ordinal not in range(128)

**Comment by kvangent** [comment]
I've pushed a change for these issues. Could you do a new pull and let me know if you have any issues?

**Comment by Maerchensarg** [comment]
Thanks, but I get the same error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\PGM\PokeAlarm-master\alarms\alarm_manager.py", line 63, in run
    self.trigger_pkmn(data['message'])
  File "D:\PGM\PokeAlarm-master\alarms\alarm_manager.py", line 119, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "D:\PGM\PokeAlarm-master\alarms\telegram_alarm.py", line 20, in pokemon_alert
    header = replace(self.header, pkinfo)
  File "D:\PGM\PokeAlarm-master\alarms\utils.py", line 137, in replace
    s = s.replace("<{}>".format(key), str(pkinfo[key]).encode('utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 4: ordinal not in range(128)

**Comment by kvangent** [comment]
@Maerchensarg Are you using text substitution?

**Comment by Maerchensarg** [comment]
Nope. I freshly redownloaded the files, put my Telegram stuff into the config and activated some Pokemon. The error turns up when a Pokemon was triggered. When it will be ignored everything seems to be fine.

**Comment by neutron666** [comment]
Same error for me

**Comment by kvangent** [comment]
Which pokemon was triggering it?

I've just pushed a new commit - could you both try again?

**Comment by Maerchensarg** [comment]
For example:

2016-08-07 14:43:42,519 [     alarm_manager] [   INFO] Weedle ignored: notify not enabled.
2016-08-07 14:43:42,535 [     alarm_manager] [   INFO] Pidgey notication was triggered!
Exception in thread Thread-1:

With the new build I get:

2016-08-07 14:45:00,904 [     alarm_manager] [   INFO] Pidgeotto notication was triggered!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\PGM\PokeAlarm-master\alarms\alarm_manager.py", line 63, in run
    self.trigger_pkmn(data['message'])
  File "D:\PGM\PokeAlarm-master\alarms\alarm_manager.py", line 119, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "D:\PGM\PokeAlarm-master\alarms\telegram_alarm.py", line 20, in pokemon_alert
    header = replace(self.header, pkinfo)
  File "D:\PGM\PokeAlarm-master\alarms\utils.py", line 138, in replace
    val = str(pkinfo[key]).encode('utf-8')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 4: ordinal not in range(128)

Seems to be the same.

**Comment by kvangent** [comment]
@Maerchensarg Is this after the last commit?

**Comment by kvangent** [comment]
Ok, I think it should be working now.

**Comment by Maerchensarg** [comment]
Works for me. Thanks a lot!
