### ISSUE TITLE
Need to change URL for icons

### ISSUE THREAD

**Issue by panix187** [kvangent/PokeAlarm#38]
2016-08-07 17:26:57,462 [     alarm_manager] [   INFO] Bulbasaur notication was triggered!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/PokeAlarm/alarms/alarm_manager.py", line 63, in run
    self.trigger_pkmn(data['message'])
  File "/root/PokeAlarm/alarms/alarm_manager.py", line 119, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "/root/PokeAlarm/alarms/slack_alarm.py", line 35, in pokemon_alert
    icon_url='https://raw.githubusercontent.com/AHAAAAAAA/PokemonGo-Map/master/static/icons/{id:d}.png'.format(**pkinfo)
ValueError: Unknown format code 'd' for object of type 'str'

I'm not familiar with git.  Otherwise, I'd do a PR to try and fix it.

https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/static/icons 

should be the new URL, right?

**Comment by kvangent** [comment]
Good catch, I'll push a change in a moment.

**Comment by panix187** [comment]
I had to change {id:d} to just {id} also fyi

**Comment by kvangent** [comment]
I've pushed the changes. I would appreciate if you would do a fresh pull and confirm that they work.
