### ISSUE TITLE
Telegram notification issue (after network failure?)

### ISSUE THREAD

**Issue by Imoq** [kvangent/PokeAlarm#40]
Telegram notification was working perfectly, and I was out hunting but then I noticed that my map stopped responding for about 4-5 minutes so I assume it was a home network issue (connection to internet loss or something). Some time later, I noticed some rare Pokémon had appeared but PokeAlarm never notified via Telegram. When I came back home, I found this on the console:

> 2016-08-07 14:41:57,697 [     alarm_manager] [   INFO] Zubat ignored: notify not set to "True".
2016-08-07 14:42:20,688 [     alarm_manager] [   INFO] Zubat ignored: notify not set to "True".
2016-08-07 14:42:29,698 [     alarm_manager] [   INFO] Onix notication was triggered!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/root/PokeAlarm/alarms/alarm_manager.py", line 54, in run
    self.trigger_pkmn(data['message'])
  File "/root/PokeAlarm/alarms/alarm_manager.py", line 85, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "/root/PokeAlarm/alarms/telegram_alarm.py", line 26, in pokemon_alert
    message = self.client.sendMessage(self.channel, '<b>' + notification_text + '</b> \n' + gmaps_link + '\n' + time_text, parse_mode='HTML', disable_web_page_preview='Fals
e')
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 240, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 229, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 135, in request_encode_body
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 223, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self, url, "Read timed out. (read timeout=%s)" % read_timeout)
ReadTimeoutError: HTTPSConnectionPool(host=u'api.telegram.org', port=443): Read timed out. (read timeout=30)

>^CKeyboardInterrupt
Traceback (most recent call last):
  File "runwebhook.py", line 57, in <module>
    server.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 349, in serve_forever
    self._stop_event.wait()
  File "/usr/local/lib/python2.7/dist-packages/gevent/event.py", line 207, in wait
    return self._wait(timeout)
  File "/usr/local/lib/python2.7/dist-packages/gevent/event.py", line 117, in _wait
    gotit = self._wait_core(timeout)
  File "/usr/local/lib/python2.7/dist-packages/gevent/event.py", line 95, in _wait_core
    result = self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
KeyboardInterrupt
root@raspberrypi:~/PokeAlarm# ^C

I *believe* this is related to the (potential) network outage but I am not sure.

**Comment by kvangent** [comment]
Yes, it is because of the network outage. The Telegram package apparently doesn't catch timeouts. I'll look into catching the error.

**Comment by kvangent** [comment]
I've put it some basic Error catching in telegram in the latest push. Please try a new pull and let me know if this solves the issue for you.

**Comment by Imoq** [comment]
Notifications seem to be working fine now, thank you very much! I will close this issue.
