### ISSUE TITLE
Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by felixvd** [kvangent/PokeAlarm#41]
I have the map running fine on my server but the PokeAlarm script refuses to run because the websocket module is missing. I tried to install it, but get more errors. See below:

```
root@myserver:~/PokeAlarm# python runwebhook.py 
Traceback (most recent call last):
  File "runwebhook.py", line 16, in <module>
    from alarms.alarm_manager import Alarm_Manager
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/PokeAlarm/alarms/alarm_manager.py", line 14, in <module>
    from pushbullet_alarm import Pushbullet_Alarm
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/PokeAlarm/alarms/pushbullet_alarm.py", line 4, in <module>
    from pushbullet import PushBullet
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/__init__.py", line 4, in <module>
    from .listener import Listener
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/listener.py", line 9, in <module>
    import websocket
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named websocket
root@myserver:~/PokeAlarm# pip install websocket
Downloading/unpacking websocket
  Downloading websocket-0.2.1.tar.gz (195kB): 195kB downloaded
  Running setup.py (path:/tmp/pip_build_root/websocket/setup.py) egg_info for package websocket
    
Requirement already satisfied (use --upgrade to upgrade): gevent in /usr/local/lib/python2.7/dist-packages (from websocket)
Requirement already satisfied (use --upgrade to upgrade): greenlet in /usr/local/lib/python2.7/dist-packages (from websocket)
Installing collected packages: websocket
  Running setup.py install for websocket
    
Successfully installed websocket
Cleaning up...
root@fvdvpn:~/PokeAlarm# python runwebhook.py 
Traceback (most recent call last):
  File "runwebhook.py", line 16, in <module>
    from alarms.alarm_manager import Alarm_Manager
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/PokeAlarm/alarms/alarm_manager.py", line 14, in <module>
    from pushbullet_alarm import Pushbullet_Alarm
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/root/PokeAlarm/alarms/pushbullet_alarm.py", line 4, in <module>
    from pushbullet import PushBullet
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/__init__.py", line 4, in <module>
    from .listener import Listener
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/listener.py", line 17, in <module>
    class Listener(Thread, websocket.WebSocketApp):
AttributeError: 'module' object has no attribute 'WebSocketApp'
```

pip install -r requirements.txt terminates without errors. I am running python version 2.7.6 on Ubuntu 14.04. I suppose I could try setting up a separate python environment with 2.7.11 but I'm not feeling too great about the prospect. Thanks in advance.

**Comment by kvangent** [comment]
Are you sure that pip install -r requirements doesn't give you any errors? It looks like you have an outdated version of gevent. Try to run `pip install setuptools` and then run the requirements again.

**Comment by felixvd** [comment]
`pip install setuptools --upgrade` gives:

```
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

And `pip install -r requirements.txt --upgrade` the same, with all the modules:

```
root@myserver:~/PokeAlarm# pip install -r requirements.txt --upgrade
Requirement already up-to-date: Flask==0.11.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: configargparse==0.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: pushbullet.py==0.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: slacker==0.9.24 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: twilio==5.4.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: telepot==8.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: gevent==1.1.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: geocoder==1.15.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: requests>=2.2.1 in /usr/local/lib/python2.7/dist-packages (from slacker==0.9.24->-r requirements.txt (line 4))
Requirement already up-to-date: httplib2>=0.7 in /usr/local/lib/python2.7/dist-packages (from twilio==5.4.0->-r requirements.txt (line 5))
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from twilio==5.4.0->-r requirements.txt (line 5))
Requirement already up-to-date: pytz in /usr/local/lib/python2.7/dist-packages (from twilio==5.4.0->-r requirements.txt (line 5))
Requirement already up-to-date: urllib3==1.9.1 in /usr/local/lib/python2.7/dist-packages (from telepot==8.3->-r requirements.txt (line 6))
Requirement already up-to-date: greenlet>=0.4.9 in /usr/local/lib/python2.7/dist-packages (from gevent==1.1.2->-r requirements.txt (line 7))
Cleaning up...

```

**Comment by kvangent** [comment]
My guess is that you need to update python then. Is there a reason you are running an older version?

**Comment by felixvd** [comment]
The server is running my VPN and I didn't want to risk breaking it with an OS upgrade unless there's a good reason. Ohwell, I guess I'll try it.

**Comment by kvangent** [comment]
You can upgrade python without an upgrade to the OS.

**Comment by kvangent** [comment]
@
