### ISSUE TITLE
Traceback error when running 'runwebhook.py'

### ISSUE THREAD

**Issue by asadaizaz** [kvangent/PokeAlarm#43]
```
Traceback (most recent call last):
  File "C:\Users\Asad\Desktop\Pokemon go dev\PokemonGo-Map\PokeAlarm\runwebhook.py", line 54, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "C:\Users\Asad\Desktop\Pokemon go dev\PokemonGo-Map\PokeAlarm\alarms\alarm_manager.py", line 28, in __init__
    settings = json.load(file)
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 6 column 4 (char 93)
```

**Comment by kvangent** [comment]
Your JSON config isn't correct. Try using http://www.jsoneditoronline.org/ to make sure you arent' missing something. (i looks like a comma at the end of line 5)
