### ISSUE TITLE
Type Error: unsupported operand types

### ISSUE THREAD

**Issue by dmtdabs** [kvangent/PokeAlarm#44]
Hello there,

After running PokeAlarm for a bit it stops with this error.

2016-08-07 11:14:49,699 [     alarm_manager] [   INFO] Horsea notication was triggered!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/pinchemac/Downloads/PokemonGo-Map-develop-5/PokeAlarm/alarms/alarm_manager.py", line 63, in run
    self.trigger_pkmn(data['message'])
  File "/Users/pinchemac/Downloads/PokemonGo-Map-develop-5/PokeAlarm/alarms/alarm_manager.py", line 108, in trigger_pkmn
    'addr': get_address(lat, lng),
  File "/Users/pinchemac/Downloads/PokemonGo-Map-develop-5/PokeAlarm/alarms/utils.py", line 93, in get_address
    return loc.housenumber + " " + loc.street
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by kvangent** [comment]
Make sure you update to the most recent version.
