### ISSUE TITLE
Telegram notification issue

### ISSUE THREAD

**Issue by prolearner** [kvangent/PokeAlarm#47]
i get this error like ten minutes after the startup of the program on OSX:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/riccardo/MEGA/GithubProjects/PokeAlarm/alarms/alarm_manager.py", line 63, in run
    self.trigger_pkmn(data['message'])
  File "/Users/riccardo/MEGA/GithubProjects/PokeAlarm/alarms/alarm_manager.py", line 119, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "/Users/riccardo/MEGA/GithubProjects/PokeAlarm/alarms/telegram_alarm.py", line 22, in pokemon_alert
    message = self.client.sendMessage(self.channel, '<b>' + header + '</b> \n' + body_text, parse_mode='HTML', disable_web_page_preview='False')
  File "/usr/local/lib/python2.7/site-packages/telepot/__init__.py", line 240, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python2.7/site-packages/telepot/__init__.py", line 229, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 141, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 575, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 455, in recv
    return self.read(buflen)
  File "/usr/local/lib/python2.7/site-packages/gevent/_sslgte279.py", line 310, in read
    return self._sslobj.read(len or 1024)
ProtocolError: ('Connection aborted.', error(54, 'Connection reset by peer'))

^CKeyboardInterrupt
Traceback (most recent call last):
  File "runwebhook.py", line 60, in <module>
    server.serve_forever()
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 349, in serve_forever
    self._stop_event.wait()
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 207, in wait
    return self._wait(timeout)
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 117, in _wait
    gotit = self._wait_core(timeout)
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 95, in _wait_core
    result = self.hub.switch()
  File "/usr/local/lib/python2.7/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)`

i don't know what may be the cause but googling up it seems related to a bad thread handling

**Comment by kvangent** [comment]
For whatever reason, Telegram aborted the connection. It's probably a fluke thing like a momentary drop in connection. If you get it again let me know, I'll try to work on some better error handling since the Telegram package doesn't seem to do it.


-------- Original message --------

**Comment by prolearner** [comment]
it happened three times today, it would be nice if you could simply ignore it

**Comment by kvangent** [comment]
Can you let me know what your set up is?

-------- Original message --------

**Comment by prolearner** [comment]
Python 2.7.11, node v4.4.7, OSX 10.11.6, what else do you need?

**Comment by kvangent** [comment]
What arguements do you use to run them from commandline?

**Comment by prolearner** [comment]
no argumento from command line, all i did was to modify the alarm.json file and run `python runwebhook.py`

**Comment by kvangent** [comment]
Ok, I'll look into it.

**Comment by prolearner** [comment]
it happened 2 times more, i'm sorry if i said after 10 minutes from startup, it's more like 50 or 60 minutes

**Comment by kvangent** [comment]
I just pushed a new commit... This should catch the error and retry a few times. Hopefully this handles the problem. Let me know if it works.

**Comment by prolearner** [comment]
thanks for the quick fix, it handles the problem perfectly without missing any notification:

    alarm_manager] [   INFO] Dragonair notication was triggered!
    telegram_alarm] [  ERROR] ('Connection aborted.', error(54,     'Connection reset by peer'))
    telegram_alarm] [  ERROR] Error sending telegram alert. 1 attempt of 5.
    connectionpool] [   INFO] Starting new HTTPS connection (2): api.telegram.org
    alarm_manager] [   INFO] Pidgey ignored: notify not enabled.

**Comment by kvangent** [comment]
Great!
