### ISSUE TITLE
Connection terminated

### ISSUE THREAD

**Issue by wowfood** [kvangent/PokeAlarm#6]
After running the alarm for a short while I get the following error message.

2016-07-29 21:48:09,318 [connectionpool] [  DEBUG] "POST /v2/pushes HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\Users\AidenEades\Documents\PokeAlarm\runwebhook.py", line 45, in <module>
    app.run(debug=config['DEBUG'],host=config['HOST'], port=config['PORT'])
  File "C:\Python27\lib\site-packages\flask\app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
    inner()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 659, in inner
    srv.serve_forever()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "C:\Python27\lib\SocketServer.py", line 227, in serve_forever
    self._handle_request_noblock()
  File "C:\Python27\lib\SocketServer.py", line 286, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 641, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 694, in finish
    self.wfile.flush()
  File "C:\Python27\lib\socket.py", line 301, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 10053] An established connection was aborted by the software in your host machine

Any ideas?  (My first guess is firewall but not entirely sure, don't want to drop my entire firewall just to test if this works y'know?|)

**Comment by wowfood** [comment]
Disabled firewall, had the same thing happen again shortly after sending a pushbullet notification.

Additionally this time I spotted this bit just above the error, repeated and had it appear again also so think they might be related.

c:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by shme14** [comment]
Ya I had it happen too: 
`
C:\Users\Jamie\Documents\GitHub\PokeAlarm>python runwebhook.py
2016-07-29 17:23:32,421 [connectionpool] [   INFO] Starting new HTTPS connection (1): api.pushbullet.com
2016-07-29 17:23:33,494 [pushbullet_alarm] [   INFO] Pushbullet Alarm intialized
2016-07-29 17:23:33,740 [ alarm_manager] [   INFO] Alarm not activated: slack because value not set to "True"
2016-07-29 17:23:33,743 [ alarm_manager] [   INFO] Alarm not activated: twilio because value not set to "True"
2016-07-29 17:24:12,602 [ alarm_manager] [   INFO] Rattata notification was not triggered because alarm is disabled.
2016-07-29 17:25:00,786 [ alarm_manager] [   INFO] Weedle notification was not triggered because alarm is disabled.
2016-07-29 17:25:06,530 [ alarm_manager] [   INFO] Tentacool notication was triggered!
2016-07-29 17:25:06,532 [connectionpool] [   INFO] Resetting dropped connection: api.pushbullet.com
2016-07-29 17:25:07,191 [connectionpool] [  DEBUG] "POST /v2/pushes HTTP/1.1" 200 None
2016-07-29 17:25:07,197 [ alarm_manager] [   INFO] Rattata notification was not triggered because alarm is disabled.
2016-07-29 17:36:10,479 [ alarm_manager] [   INFO] Rattata notification was not triggered because alarm is disabled.
2016-07-29 17:42:28,354 [ alarm_manager] [   INFO] Rattata notification was not triggered because alarm is disabled.
2016-07-29 17:44:36,892 [ alarm_manager] [   INFO] Meowth notication was triggered!
2016-07-29 17:44:36,894 [connectionpool] [   INFO] Resetting dropped connection: api.pushbullet.com
2016-07-29 17:44:37,426 [connectionpool] [  DEBUG] "POST /v2/pushes HTTP/1.1" 200 None
2016-07-29 17:47:48,676 [ alarm_manager] [   INFO] Weedle notification was not triggered because alarm is disabled.
2016-07-29 17:51:59,329 [ alarm_manager] [   INFO] Rattata notification was not triggered because alarm is disabled.
2016-07-29 17:53:03,480 [ alarm_manager] [   INFO] Shellder notication was triggered!
2016-07-29 17:53:03,482 [connectionpool] [   INFO] Resetting dropped connection: api.pushbullet.com
2016-07-29 17:53:04,582 [connectionpool] [  DEBUG] "POST /v2/pushes HTTP/1.1" 200 None
Traceback (most recent call last):
  File "runwebhook.py", line 45, in <module>
    app.run(debug=config['DEBUG'],host=config['HOST'], port=config['PORT'])
  File "C:\Python27\lib\site-packages\flask\app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 694, in run_simple
    inner()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 659, in inner
    srv.serve_forever()
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "C:\Python27\lib\SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "C:\Python27\lib\SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\SocketServer.py", line 654, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 713, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 283, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 10053] An established connection was aborted by the software in your host machine

C:\Users\Jamie\Documents\GitHub\PokeAlarm>pause
Press any key to continue . . .`

**Comment by kvangent** [comment]
The first error is because the socket is closing while the server trys to respond. I only have my phone right now, but if you checkout the reddit thread I posted a temporary fix for it.

**Comment by wowfood** [comment]
Posting the reddit fix here so it's easier to find for others.

Go to /pgom/utils.py and look for the following line towards the end of the file.

requests.post(w, json=data, timeout=(None, 1))

Change the 1 to a 5 and that should fix it, if it doesn't keep upping the number (up to 10) until the problem stops.

**Comment by kvangent** [comment]
@wowfood Sorry for the late response to this. I've updated the Readme to include the fix.

**Comment by brandonshults** [comment]
Thank you for your work on this project.  I know you have posted a solution, but I'm wondering how hard it would be to bulletproof PokeAlarm so that if the timeout does occur, the whole thing doesn't crash?  Or does the webhook server stop broadcasting?

**Comment by kvangent** [comment]
It is apparently a pain in the ass - I'm brand new to Flask and Python, but it is an error that occurs outside of the framework. In a deployment environment the stack would just ignore it and keep running, but in a development environment it seems to bring everything to a standstill. I'm looking into alternatives but haven't had much luck so far.

**Comment by brandonshults** [comment]
Awesome, thank you, I haven't written Python since I wrote a chess AI nearly a decade ago but when I get some time if I can create a reliable repro I will gladly look at it too.
