### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by roflinger** [kvangent/PokeAlarm#65]
with the first found pokemon: 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "D:\Users\Downloads\PokeAlarm-master\PokeAlarm-master\alarms\alarm_manager.py", line 66, in run
    self.trigger_pkmn(data['message'])
  File "D:\Users\Downloads\PokeAlarm-master\PokeAlarm-master\alarms\alarm_manager.py", line 123, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "D:\Users\Downloads\PokeAlarm-master\PokeAlarm-master\alarms\pushbullet_alarm.py", line 21, in pokemon_alert
    notify_text = replace(self.notify_text, pkinfo)
  File "D:\Users\Downloads\PokeAlarm-master\PokeAlarm-master\alarms\utils.py", line 153, in replace
    s = s.replace("<{}>".format(key), pkinfo[key])
TypeError: expected a string or other character buffer object

**Comment by kvangent** [comment]
Could you pull the latest commit and try again?

**Comment by DyonR** [comment]
I had the same issue, for me it is working now.

**Comment by kvangent** [comment]
@DyonR Great, thanks.

**Comment by roflinger** [comment]
also working here, was on tour sorry :D
