### ISSUE TITLE
[USER] Exception in thread pkmn when trying to Notify

### ISSUE THREAD

**Issue by jameson167** [kvangent/PokeAlarm#73]
It's Me Again! Thanks for all the help earlier. I have now moved my entire configuration over to an Amazon AWS Box + Proxy setup. I have gotten all the maps API working and the PokeAlarm is close to functioning now. The server is a Windows Server 2012 box which might be causing the issues. 

When I start the 

My Maps command is the same as earlier trailing with the
`-wh http://127.0.0.1:4000`

My PokeAlarm command is:
`python runwebhook.py -P 4000`

When I start the map it sends successful 200 POST HTTP connectionpool messages for each pokemon scanned. There are no utils errors in the debug mode. 

On the Pokealarm side if I have all pokemon turned "False" then I will continue to receive the Post info with each pokemon like so:
![image](https://cloud.githubusercontent.com/assets/20566412/17540861/d9646d90-5e6e-11e6-853d-0de98a05b445.png)

BUT (PROBLEM HERE) if I turn on some Pokemon such as Sandshrew to "TRUE" then as soon as it detects that pokemon it says "Sandshrew notification was triggered!" and then returns the following crashed errors:

```
2016-08-10 03:19:49,040 [    connectionpool] [  DEBUG] "GET /maps/api/geocode/json?latlng=34.101749%2C+-118.325578&sensor=false&language= HTTP/1.1"        200 1767
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\PoGo\PokeAlarm-master\alarms\alarm_manager.py", line 66, in run
    self.trigger_pkmn(data['message'])
  File "C:\PoGo\PokeAlarm-master\alarms\alarm_manager.py", line 123, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "C:\PoGo\PokeAlarm-master\alarms\slack_alarm.py", line 30, in pokemon_alert
    username = replace(self.username, pkinfo)
  File "C:\PoGo\PokeAlarm-master\alarms\utils.py", line 153, in replace
    s = s.replace("<{}>".format(key), pkinfo[key])
TypeError: expected a string or other character buffer object

```

![image](https://cloud.githubusercontent.com/assets/20566412/17540854/cd8b5c4a-5e6e-11e6-8b4c-df40a917fd83.png)

## Your Environment
Operating System:  Windows Server 2012 (On Amazon EC2)
Environment name and version (e.g. Python 2.7):  Python 2.7, All upgrades complete per requirements.txt

##Troubleshooting Checklist
[YES] Updated PokemonGo-Map
[YES] Updated PokeAlarm
[YES] Checked the Wiki for specified Service

**Comment by jameson167** [comment]
I used Postman to manually post a Bulbasaur per your instructions earlier.

It produced the same error as so:

```
2016-08-10 04:00:13,959 [        runwebhook] [  DEBUG] POST request received from 127.0.0.1.
2016-08-10 04:00:13,960 [            pywsgi] [   INFO] 127.0.0.1 - - [2016-08-10 04:00:13] "POST / HTTP/1.1" 200 115 0.001000
2016-08-10 04:00:13,960 [     alarm_manager] [  DEBUG] Request processed for #1
2016-08-10 04:00:13,960 [     alarm_manager] [   INFO] Bulbasaur notication was triggered!
2016-08-10 04:00:13,967 [    connectionpool] [   INFO] Starting new HTTPS connection (1): maps.googleapis.com
Exception in thread Thread-1:connectionpool] [  DEBUG] "GET /maps/api/geocode/json?latlng=42.790967%2C+-96.92792&sensor=false&language= HTTP/1.1" 200 1266
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\PoGo\PokeAlarm-master\alarms\alarm_manager.py", line 66, in run
    self.trigger_pkmn(data['message'])
  File "C:\PoGo\PokeAlarm-master\alarms\alarm_manager.py", line 123, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "C:\PoGo\PokeAlarm-master\alarms\slack_alarm.py", line 30, in pokemon_alert
    username = replace(self.username, pkinfo)
  File "C:\PoGo\PokeAlarm-master\alarms\utils.py", line 153, in replace
    s = s.replace("<{}>".format(key), pkinfo[key])
TypeError: expected a string or other character buffer object
```

![image](https://cloud.githubusercontent.com/assets/20566412/17541457/7699a634-5e74-11e6-8b81-d245548cc7ea.png)

**Comment by jameson167** [comment]
I compared the debug on my working home PC setup vs the Server and the difference is that there is no new HTTPS connection to slack.com being intiated and no POST /api/chat.postMessage"

Here is the log from a test notification sent by Postman on the working home PC:
![image](https://cloud.githubusercontent.com/assets/20566412/17541791/cfd6311a-5e77-11e6-8ce6-9d1530efe4c0.png)
(This one successfully sends a message of the Bulbasaur in to my Slack)

Here is the log for the windows server which just stops here:
![image](https://cloud.githubusercontent.com/assets/20566412/17541756/70a4b9be-5e77-11e6-847b-e90a893c29b4.png)
(No message sent)

**Comment by jameson167** [comment]
I also set up Telegram to see if it was a SLACK specific issue but netted the same exact results. Telegram works on my home PC, but when I try the same configuration on the Windows Server the notification process triggers but it hangs at this point:

![image](https://cloud.githubusercontent.com/assets/20566412/17542257/e2744286-5e7b-11e6-9736-507bd5d641ce.png)

**Comment by kvangent** [comment]
@jameson167 Are you using the most recent pull? Your issue is different than before.

**Comment by jameson167** [comment]
Yes everything is updated. The difference is this is running on a Windows 2012 Server hosted on Amazon EC2. Perhaps there is some kind of security protocol or Inbound/Outbound Rule needed?

**Comment by jameson167** [comment]
I'm back in the Discord chat if you have any free time to PM me. Think it's some small permissions issue. 
https://discord.gg/dKTSHZC user: Jameson167
