### ISSUE TITLE
Broken Pipe (Errno 32)

### ISSUE THREAD

**Issue by dmtdabs** [kvangent/PokeAlarm#8]
After running the alarm for a bit , and after receiving about 3 notification for pokemon, the following error message is displayed. 

2016-07-29 23:09:12,703 [ alarm_manager] [   INFO] Horsea notication was triggered!
2016-07-29 23:09:12,731 [connectionpool] [   INFO] Resetting dropped connection: api.pushbullet.com
2016-07-29 23:09:13,864 [connectionpool] [  DEBUG] "POST /v2/pushes HTTP/1.1" 200 None
Traceback (most recent call last):
  File "runwebhook.py", line 45, in <module>
    app.run(debug=config['DEBUG'],host=config['HOST'], port=config['PORT'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe

I don't have any idea what might cause this or where to even start to attempt to find a fix.

**Comment by Dagothur** [comment]
Hi,

I got the same:


Traceback (most recent call last):
  File "runwebhook.py", line 45, in <module>
    app.run(debug=config['DEBUG'],host=config['HOST'], port=config['PORT'])
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 297, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe

**Comment by Dagothur** [comment]
I'm using this wrapper.sh script to help keep the alerts going:

   n=0
   until [ $n -ge 15 ]
   do
      python runwebhook.py && break  # substitute your command here
      n=$[$n+1]
      sleep 5
   done

I'm hoping that when the broke pipe error strikes this thing will just restart the script (it did so when I manually killed the process).

**Comment by dmtdabs** [comment]
How do i implement your fix by using the wrapper.sh script? Could you make a pull request for it? @Dagothur

**Comment by Dagothur** [comment]
I can try, I've never done it before.

By the way it's more of a hack than a fix -- simply restarting the script if it errors.

**Comment by Dagothur** [comment]
Okay. Here: https://github.com/kvangent/PokeAlarm/pull/10 it is if you want it. I also forgot to consider that this is only going to work on linux, so if you're on Windows you'd have to rewrite it in bash.

If you're on linux, instead of starting the script itself you should do the following:

chmod +x wrapper.sh
./wrapper.sh

**Comment by dmtdabs** [comment]
Thanks for that, i really appreciate it. 

I'm actually on mac OS X , is there anything else id need to do before i can run this?

**Comment by Dagothur** [comment]
Maybe just make sure that the listener is stopped before starting it with the shell script.

**Comment by kvangent** [comment]
Sorry for the late response on this, it is actually a problem from the Map's side. The map sends the POST request with too short of a disconnect time, so when my app try to respond it finds the connection already closed. I have submitted a pull request to the main map already to correct the problem (and the time problem) but they are dragging their feet to accept it.
