### ISSUE TITLE
Jelastic ProtocolError gaierror (-3 ...

### ISSUE THREAD

**Issue by aronjanosch** [kvangent/PokeAlarm#86]
Hi,

I run pokealarm on jelastic with a dockerimage.

It works quite some Time but then the run.log file returns

08-10 23:36:07,508 [     alarm_manager] [   INFO] Abra notication was triggered!
2016-08-10 23:36:07,509 [    connectionpool] [   INFO] Resetting dropped connection: api.telegram.org
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/src/app/alarms/alarm_manager.py", line 54, in run
    self.trigger_pkmn(data['message'])
  File "/usr/src/app/alarms/alarm_manager.py", line 85, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "/usr/src/app/alarms/telegram_alarm.py", line 26, in pokemon_alert
    message = self.client.sendMessage(self.channel, '<b>' + notification_text + '</b> \n' + gmaps_link + '\n' + time_text, parse_mode='HTML', disable_web_page_preview='False')
  File "/usr/local/lib/python2.7/site-packages/telepot/__init__.py", line 240, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python2.7/site-packages/telepot/__init__.py", line 229, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 141, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 575, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 326, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 740, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python2.7/site-packages/gevent/_socketcommon.py", line 268, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
  File "/usr/local/lib/python2.7/site-packages/gevent/resolver_thread.py", line 64, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/gevent/pool.py", line 300, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 373, in get
    return self.get(block=False)
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 363, in get
    return self._raise_exception()
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 343, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/local/lib/python2.7/site-packages/gevent/threadpool.py", line 207, in _worker
    value = func(*args, **kwargs)
ProtocolError: ('Connection aborted.', gaierror(-3, 'Try again'))

**Comment by aronjanosch** [comment]
Now it doesn't start anymore

 00:10:46,663 [    connectionpool] [   INFO] Starting new HTTPS connection (1): api.telegram.org
Traceback (most recent call last):
  File "./runwebhook.py", line 51, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "/usr/src/app/alarms/alarm_manager.py", line 38, in __init__
    self.alarms.append(Telegram_Alarm(alarm))
  File "/usr/src/app/alarms/telegram_alarm.py", line 18, in __init__
    self.client.sendMessage(self.channel, 'PokeAlarm activated! We will alert this channel about pokemon.')
  File "/usr/local/lib/python2.7/site-packages/telepot/__init__.py", line 240, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python2.7/site-packages/telepot/__init__.py", line 229, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 141, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 575, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 326, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 740, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python2.7/site-packages/gevent/_socketcommon.py", line 268, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
  File "/usr/local/lib/python2.7/site-packages/gevent/resolver_thread.py", line 64, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/gevent/pool.py", line 300, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 373, in get
    return self.get(block=False)
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 363, in get
    return self._raise_exception()
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 343, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/local/lib/python2.7/site-packages/gevent/threadpool.py", line 207, in _worker
    value = func(*args, **kwargs)
urllib3.exceptions.ProtocolError: ('Connection aborted.', gaierror(-3, 'Try again'))

**Comment by aronjanosch** [comment]
New error After restarting again

Sry for Spamming but i want to provide aus much als i can :)

2016-08-11 00:14:41,249 [     alarm_manager] [   INFO] Alarm not activated: pushbullet because value not set to "True"
2016-08-11 00:14:41,250 [     alarm_manager] [   INFO] Alarm not activated: slack because value not set to "True"
2016-08-11 00:14:41,250 [     alarm_manager] [   INFO] Alarm not activated: twilio because value not set to "True"
2016-08-11 00:14:41,250 [    telegram_alarm] [   INFO] Telegram Alarm intialized
2016-08-11 00:14:41,250 [    connectionpool] [   INFO] Starting new HTTPS connection (1): api.telegram.org
2016-08-11 00:14:41,317 [     alarm_manager] [   INFO] Alarm_Manager has started!
2016-08-11 00:14:41,317 [        runwebhook] [   INFO] Webhook server running on http://https://env-7627163.jelastic.dogado.eu:80
Traceback (most recent call last):
  File "./runwebhook.py", line 57, in <module>
    server.serve_forever()
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 347, in serve_forever
    self.start()
  File "/usr/local/lib/python2.7/site-packages/gevent/baseserver.py", line 291, in start
    self.init_socket()
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 1222, in init_socket
    StreamServer.init_socket(self)
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 80, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 91, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
  File "/usr/local/lib/python2.7/site-packages/gevent/server.py", line 177, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
socket.gaierror: [Errno -2] Name does not resolve: ('https://env-7627163.jelastic.dogado.eu', 80)
Exception gevent.hub.LoopExit: LoopExit('This operation would block forever', <Hub at 0x7f20777d3690 epoll default pending=0 ref=0 fileno=4 resolver=<gevent.resolver_thread.Resolver at 0x7f20777c23d0 pool=<ThreadPool at 0x7f20777c2350 0/1/10>> threadpool=<ThreadPool at 0x7f20777c2350 0/1/10>>) in <module 'threading' from '/usr/local/lib/python2.7/threading.pyc'> ignored

**Comment by kvangent** [comment]
@aronjanosch In the future, please make sure to use the given Issue templates.

It looks like your first issue was a connection drop - If you update to the newest version PokeAlarm will try to handle these better.

The second issue looks like you have a socket already bound - it's possible that you have another program using the port or that your crash from before didn't close the socket. Try restarting your machine and trying again.

If you continue to have problems, open a ticket and follow one of the given templates.
