### ISSUE TITLE
[BUG] Pokealarm runs into an error when using telegram (Jelastic Docker)

### ISSUE THREAD

**Issue by aronjanosch** [kvangent/PokeAlarm#89]
## Problem Description
Using Jelastic. If i run PokeAlarm with Telegram it runs into an error: 
File "/usr/local/lib/python2.7/site-packages/gevent/threadpool.py", line 207, in _worker
value = func(args, **kwargs)
ProtocolError: ('Connection aborted.', gaierror(-3, 'Try again'))

After switching to Pushbullet the App runs stable

## Your Environment
Operating System:  Jelastic Dockerfile (https://hub.docker.com/r/aronjanosch/pokealarm/~/dockerfile/)
Python Version: (python:2.7-alpine`)  
PokemonGo-Map startup command: `--host 0.0.0.0 --port 80 -sd 10 -fl -wh http://********.jelastic.dogado.eu:4000`  
PokeAlarm startup command: `<-H *********.jelastic.dogado.eu -P 4000 >`

Did the issue persist after restarting the script?: yes

##Console Output

```
2016-08-11 11:20:16,732 [     alarm_manager] [   INFO] You will be notified of the following pokemon: 
Bulbasaur, Ivysaur, Venusaur, Charmander, Charmeleon, Charizard, Squirtle, Wartortle, Blastoise, Arbok, Pikachu, Raichu, Sandshrew, Sandslash, Nidorina, Nidoqueen, Nidorino, Nidoking, Clefable, Ninetales, Wigglytuff, Gloom, Vileplume, Diglett, Dugtrio, Persian, Golduck, Primeape, Growlithe, Arcanine, Poliwhirl, Poliwrath, Kadabra, Alakazam, Machoke, Machamp, Victreebel, Tentacruel, Graveler, Golem, Rapidash, Slowbro, Magneton, Farfetch'd, Doduo, Dodrio, Dewgong, Grimer, Muk, Cloyster, Haunter, Gengar, Onix, Voltorb, Electrode, Exeggcute, Exeggutor, Cubone, Marowak, Hitmonlee, Hitmonchan, Lickitung, Koffing, Weezing, Rhydon, Chansey, Tangela, Kangaskhan, Seadra, Seaking, Starmie, Mr. Mime, Scyther, Electabuzz, Magmar, Pinsir, Tauros, Gyarados, Lapras, Ditto, Jolteon, Flareon, Porygon, Omanyte, Omastar, Kabuto, Kabutops, Aerodactyl, Snorlax, Articuno, Zapdos, Moltres, Dratini, Dragonair, Dragonite, Mewtwo, Mew
2016-08-11 11:20:16,733 [     alarm_manager] [   INFO] Alarm not activated: pushbullet because value not set to "True"
2016-08-11 11:20:16,733 [     alarm_manager] [   INFO] Alarm not activated: slack because value not set to "True"
2016-08-11 11:20:16,734 [     alarm_manager] [   INFO] Alarm not activated: twilio because value not set to "True"
2016-08-11 11:20:16,734 [    telegram_alarm] [   INFO] Telegram Alarm intialized
2016-08-11 11:20:16,735 [    connectionpool] [   INFO] Starting new HTTPS connection (1): api.telegram.org
Traceback (most recent call last):
  File "./runwebhook.py", line 55, in <module>
    alarm_thread = Alarm_Manager(data_queue)
  File "/usr/src/app/alarms/alarm_manager.py", line 48, in __init__
    self.alarms.append(Telegram_Alarm(alarm))
  File "/usr/src/app/alarms/telegram_alarm.py", line 19, in __init__
    self.client.sendMessage(self.chat_id, 'PokeAlarm activated! We will alert this chat about pokemon.')
  File "/usr/local/lib/python2.7/site-packages/telepot/__init__.py", line 240, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/local/lib/python2.7/site-packages/telepot/__init__.py", line 229, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/local/lib/python2.7/site-packages/urllib3/request.py", line 141, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 575, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 326, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 740, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python2.7/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python2.7/site-packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python2.7/site-packages/gevent/_socketcommon.py", line 268, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, socktype, proto, flags)
  File "/usr/local/lib/python2.7/site-packages/gevent/resolver_thread.py", line 64, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/gevent/pool.py", line 300, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 373, in get
    return self.get(block=False)
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 363, in get
    return self._raise_exception()
  File "/usr/local/lib/python2.7/site-packages/gevent/event.py", line 343, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/local/lib/python2.7/site-packages/gevent/threadpool.py", line 207, in _worker
    value = func(*args, **kwargs)
urllib3.exceptions.ProtocolError: ('Connection aborted.', gaierror(-3, 'Try again'))
```

## Your Alarms Config

```json
{
	"alarms":[
		{
			"active":"False",
			"type":"pushbullet",
			"api_key":"**************************************************"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"YOUR_API_KEY",
			"channel":"#general"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"YOUR_API_KEY",
			"auth_token":"YOUR_AUTH_TOKEN",
			"from_number":"YOUR_FROM_NUM",
			"to_number":"YOUR_TO_NUM"
		},
		{
			"active": "True",
			"type":"telegram",
			"bot_token":"*****************************************************",
			"chat_id":"*************"
		},
		{
			"active": "False",
			"type": "pushover",
			"app_token": "YOUR_APP_TOKEN",
			"user_key": "YOUR_USER_KEY"
		}
	],
	"pokemon":{
```

##Troubleshooting Checklist
[ x] Most recent version of PokemonGo-Map
[ x] Most recent version of PokemonGo-Map
[ x] Checked the Wiki for specified Service

**Comment by kvangent** [comment]
@aronjanosch Your error appears to be an issue trying to resolve the telegram host-name. I'm am not familier with jelastic, but it is either an issue with your docker setup or with jelastic itself.

**Comment by aronjanosch** [comment]
i could try to use another service. 
i just kinda kopied the official dockerfile from PokemonGo-Map and added s2sphere==0.2.4 to the requirements.txt and then used the automated build from hub.docker.com

**Comment by kvangent** [comment]
There is a PR for docker file right now. You could try that and let me know how it works. https://github.com/kvangent/PokeAlarm/pull/84

**Comment by aronjanosch** [comment]
yea saw that and thats nearly the same dockerfile i use, except mine also contains the argument -h

I run the docker images in 2 seperate enviroments and everything works perfectly fine with pushbullet. It running right now without errors

```
2016-08-11 13:23:14,275 [     alarm_manager] [   INFO] Rattata ignored: notify not enabled.
2016-08-11 13:23:24,312 [     alarm_manager] [   INFO] Nidoran♀ ignored: notify not enabled.
2016-08-11 13:23:24,321 [     alarm_manager] [   INFO] Pidgey ignored: notify not enabled.
2016-08-11 13:23:27,700 [     alarm_manager] [   INFO] Zubat ignored: notify not enabled.
2016-08-11 13:23:34,320 [     alarm_manager] [   INFO] Eevee ignored: notify not enabled.
```



# My Dockerfile 
```
# Basic docker image for PokeAlarm
# Usage:
#   docker build -t pokealarm .
#   docker run -d -P pokealarm 

FROM python:2.7-alpine

# Default port the webserver runs on
EXPOSE 4000

# Working directory for the application
WORKDIR /usr/src/app

# Set Entrypoint with hard-coded options
ENTRYPOINT ["python", "./runwebhook.py"]

# Set default options when container is run without any command line arguments
CMD ["-h"]

# Install required system packages
RUN apk add --no-cache ca-certificates
RUN apk add --no-cache bash git openssh

COPY requirements.txt /usr/src/app/

RUN apk add --no-cache build-base \
 && pip install --no-cache-dir -r requirements.txt \
 && apk del build-base


# Copy everything to the working directory (Python files, templates, config) in one go.
COPY . /usr/src/app/
```

# The Dockerfile from the PR

```
+# Basic docker image for PokeAlarm
 +# It runs with the webhook -wh http://127.0.0.1:4000
 +# Usage:
 +#   docker build -t pokealarm
 +#   docker run -d --net container:PokemonGo-Map --name PokeAlarm -P pokealarm
 +# Change "PokemonGo-Map" to the name of your PokemonGo-Map docker
 +
 +FROM python:2.7-alpine
 +
 +# Default port the webserver runs on
 +EXPOSE 4000
 +
 +# Working directory for the application
 +WORKDIR /usr/src/app
 +
 +# Set Entrypoint with hard-coded options
 +ENTRYPOINT ["python", "./runwebhook.py"]
 +
 +# Install required system packages
 +RUN apk add --no-cache ca-certificates
 +RUN apk add --no-cache bash git openssh
 +
 +COPY requirements.txt /usr/src/app/
 +
 +RUN apk add --no-cache build-base \
 + && pip install --no-cache-dir -r requirements.txt \
 + && apk del build-base
 +
 +# Copy everything to the working directory (Python files, templates, config) in one go.
 +COPY . /usr/src/app/
```

**Comment by annessi** [comment]
I had a problem with the -h argument so i removed it. 
Anyway I've been using this configuration for about a day and it's working great with telegram.

**Comment by aronjanosch** [comment]
do you run your enviroments on jelastic? cause if not then its a problem on their side.

**Comment by annessi** [comment]
I'm running docker on my synology server.

**Comment by kvangent** [comment]
@aronjanosch The issue seems to be dns related. Id the programs are running on the same machines try 127.0.0.1 instead of hostname.

**Comment by aronjanosch** [comment]
actually i created 2 enviroments with and i get 2 sperated adresses from jelastic. and i thought dockers are pretty much closed from each other.
but I'll try to do this later and report and i'll setup one enviroment with 2 dockers in it.

**Comment by kvangent** [comment]
If you can open up the container and attempt to ping the address, ,it might verify if its a dns issue or not.

You can also try manually adding in a DNS server to google when you build the container.

**Comment by aronjanosch** [comment]
guess im too noobish to do that. i understand what you are saying but i actually dont know how to do that espacially with jelastic and docker. Im pretty new in da biz :grin:

**Comment by kvangent** [comment]
You can run a docker container interactively with -i -t. But I don't know if containers built from python will allow you to ping, I've only worked with Ubuntu ones.

**Comment by kvangent** [comment]
@aronjanosch did you get this problem figured out?
