### ISSUE TITLE
[BUG] PokeAlarm occassionally dies when using PushBullet

### ISSUE THREAD

**Issue by brettgus** [kvangent/PokeAlarm#90]
## Your Environment

Operating System:  Ubuntu 16.04
Python Version: (use `python -V`)  2.7.12
PokemonGo-Map startup command: `<cmd>`  
PokeAlarm startup command: `<cmd>` nohup python runwebhook.py -H 0.0.0.0 -P 6701

Did the issue persist after restarting the script?: yes/no  No, issue is intermittent

##Console Output

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user/PokeAlarm/alarms/alarm_manager.py", line 64, in run
    self.trigger_pkmn(data['message'])
  File "/home/user/PokeAlarm/alarms/alarm_manager.py", line 128, in trigger_pkmn
    alarm.pokemon_alert(pkinfo)
  File "/home/user/PokeAlarm/alarms/pushbullet_alarm.py", line 24, in pokemon_alert
    push = self.sender.push_link(notify_text, link, body=body_text)
  File "/home/user/.local/lib/python2.7/site-packages/pushbullet/channel.py", line 29, in push_link
    return self._push(data)
  File "/home/user/.local/lib/python2.7/site-packages/pushbullet/channel.py", line 36, in _push
    return self._account._push(data)
  File "/home/user/.local/lib/python2.7/site-packages/pushbullet/pushbullet.py", line 267, in _push
    raise PushError(r.text)
PushError: {"error":{"code":"server_error","type":"server_error","message":"An unhandled server error occurred.","cat":"+:3"},"error_code":"server_error"}

```

## Your Alarms Config

```json
{
	"alarms":[
		{
			"active": "True",
			"type":"pushbullet",
			"api_key":"REMOVED",
			"channel":"REMOVED"
		},
		{
			"active": "False",
			"type":"slack",
			"api_key":"",
			"channel":"#general"
		},
		{
			"active": "False",
			"type":"twilio",
			"account_sid":"",
			"auth_token":"",
			"to_number":"+11234567890",
			"from_number":"+11234567890"
		},
		{
		        "active": "False",
		        "type":"telegram",
		        "chat_id":"your bot chat ID",
		        "bot_token":"your bot API"
    		}
	],
	"pokemon":{
		"Bulbasaur":"False",
		"Ivysaur":"False",
		"Venusaur":"True",
		"Charmander":"True",
		"Charmeleon":"True",
		"Charizard":"true",
		"Squirtle":"False",
		"Wartortle":"False",
		"Blastoise":"True",
		"Caterpie":"False",
		"Metapod":"False",
		"Butterfree":"False",
		"Weedle":"False",
		"Kakuna":"False",
		"Beedrill":"False",
		"Pidgey":"False",
		"Pidgeotto":"False",
		"Pidgeot":"False",
		"Rattata":"False",
		"Raticate":"False",
		"Spearow":"False",
		"Fearow":"False",
		"Ekans":"False",
		"Arbok":"True",
		"Pikachu":"False",
		"Raichu":"True",
		"Sandshrew":"False",
		"Sandslash":"True",
		"Nidoran♀":"False",
		"Nidorina":"False",
		"Nidoqueen":"True",
		"Nidoran♂":"False",
		"Nidorino":"False",
		"Nidoking":"True",
		"Clefairy":"False",
		"Clefable":"True",
		"Vulpix":"False",
		"Ninetales":"True",
		"Jigglypuff":"False",
		"Wigglytuff":"False",
		"Zubat":"False",
		"Golbat":"False",
		"Oddish":"False",
		"Gloom":"False",
		"Vileplume":"True",
		"Paras":"False",
		"Parasect":"False",
		"Venonat":"False",
		"Venomoth":"False",
		"Diglett":"False",
		"Dugtrio":"True",
		"Meowth":"False",
		"Persian":"True",
		"Psyduck":"False",
		"Golduck":"True",
		"Mankey":"False",
		"Primeape":"True",
		"Growlithe":"True",
		"Arcanine":"True",
		"Poliwag":"False",
		"Poliwhirl":"False",
		"Poliwrath":"True",
		"Abra":"False",
		"Kadabra":"True",
		"Alakazam":"True",
		"Machop":"False",
		"Machoke":"True",
		"Machamp":"True",
		"Bellsprout":"False",
		"Weepinbell":"False",
		"Victreebel":"True",
		"Tentacool":"False",
		"Tentacruel":"True",
		"Geodude":"False",
		"Graveler":"True",
		"Golem":"True",
		"Ponyta":"True",
		"Rapidash":"True",
		"Slowpoke":"False",
		"Slowbro":"True",
		"Magnemite":"False",
		"Magneton":"False",
		"Farfetch'd":"True",
		"Doduo":"False",
		"Dodrio":"True",
		"Seel":"False",
		"Dewgong":"False",
		"Grimer":"True",
		"Muk":"True",
		"Shellder":"False",
		"Cloyster":"False",
		"Gastly":"False",
		"Haunter":"False",
		"Gengar":"True",
		"Onix":"False",
		"Drowzee":"False",
		"Hypno":"False",
		"Krabby":"False",
		"Kingler":"False",
		"Voltorb":"False",
		"Electrode":"True",
		"Exeggcute":"False",
		"Exeggutor":"True",
		"Cubone":"False",
		"Marowak":"True",
		"Hitmonlee":"False",
		"Hitmonchan":"True",
		"Lickitung":"False",
		"Koffing":"False",
		"Weezing":"True",
		"Rhyhorn":"False",
		"Rhydon":"True",
		"Chansey":"False",
		"Tangela":"False",
		"Kangaskhan":"False",
		"Horsea":"False",
		"Seadra":"False",
		"Goldeen":"False",
		"Seaking":"False",
		"Staryu":"False",
		"Starmie":"False",
		"Mr. Mime":"False",
		"Scyther":"False",
		"Jynx":"False",
		"Electabuzz":"False",
		"Magmar":"False",
		"Pinsir":"False",
		"Tauros":"False",
		"Magikarp":"False",
		"Gyarados":"True",
		"Lapras":"True",
		"Ditto":"True",
		"Eevee":"False",
		"Vaporeon":"True",
		"Jolteon":"True",
		"Flareon":"True",
		"Porygon":"True",
		"Omanyte":"False",
		"Omastar":"False",
		"Kabuto":"True",
		"Kabutops":"True",
		"Aerodactyl":"True",
		"Snorlax":"True",
		"Articuno":"True",
		"Zapdos":"True",
		"Moltres":"True",
		"Dratini":"False",
		"Dragonair":"True",
		"Dragonite":"True",
		"Mewtwo":"True",
		"Mew":"True"
	}
}

```

##Troubleshooting Checklist
[X] Most recent version of PokemonGo-Map
[X] Most recent version of PokemonGo-Map
[ ] Checked the Wiki for specified Service

**Comment by kvangent** [comment]
@brettgus From the look of it Pushbullet is throwing some errors in the response. This could be because of some connectivity problems.  Have you updated your PokeAlarm copy in the last day? I added some basic error handling that should catch errors and attempt to reconnect. I don't seem to see an indication that this version is trying that.

**Comment by kvangent** [comment]
Yeah that is my mistake, I'll update it.

**Comment by kvangent** [comment]
@brettgus Are you still having any issues with this?

**Comment by brettgus** [comment]
Seems to be working

**Comment by kvangent** [comment]
Great, thank you.
