### ISSUE TITLE
[BUG] Thread Exception since new PokemonGoMap Update

### ISSUE THREAD

**Issue by jameson167** [kvangent/PokeAlarm#97]
They recently updated PokemonGoMap to work with Lured pokestops again. Perhaps there is a change that has broken the PokeAlarm? When starting the alarm it receives plenty of webhook posts but after receiving 1 pokemon it produces this exception error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\PoGo\PokeAlarm\alarms\alarm_manager.py", line 64, in run
    log.debug("Request processed for #%s" % data['message']['pokemon_id'])
KeyError: 'pokemon_id'

```

## Your Environment

Operating System:  Windows Server 2012
Python Version: (use `python -V`)  2.1.7

Did the issue persist after restarting the script?:  yes

##Console Output
Debug Mode 
![image](https://cloud.githubusercontent.com/assets/20566412/17603905/1330d19e-5fc8-11e6-9759-5a71ea76f799.png)

PokeAlarm Command:
`python runwebhook.py -P 4067 --debug`

## Console Outputs

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\PoGo\PokeAlarm\alarms\alarm_manager.py", line 64, in run
    log.debug("Request processed for #%s" % data['message']['pokemon_id'])
KeyError: 'pokemon_id'
```

**Comment by kvangent** [comment]
@jameson167 Could be. I will investigate.

**Comment by kvangent** [comment]
Last commit should handle this issue.
